In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import csv


# 設定 Pandas 顯示選項，以便顯示所有行和列
pd.set_option('display.max_rows', None)  # 顯示所有行
pd.set_option('display.max_columns', None)  # 顯示所有列

## SENTO 題庫

In [3]:
# 紀錄次數 = 迭代次數次(初始解)
run_time = 20 # 執行次數
problem = ["01","02"]
algorithm = "BSMASCA_V1_RL_015_25"

result_table = np.zeros([len(problem),run_time],dtype=int)

# 循環瀏覽您的 CSV 文件
for i in range(run_time):
    for j, prob in enumerate(problem):
        best_df_name = f"runtime_{i}_prob_{prob}_algo_{algorithm}.csv" # 最佳解
        df_path = f"output/{algorithm}/SENT/{best_df_name}" # 最佳解
        with open(df_path, 'r') as csvfile:
            text = csvfile.read() # 讀取
            match = re.search(r'(\d+\.\d+)', text).group(1)
            result_table[j,i] = float(match)

df = pd.DataFrame(result_table)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,7772,7772,7772,7772,7772,7772,7772,7772,7772,7772,7772,7772,7772,7772,7772,7772,7772,7772,7772,7772
1,8722,8722,8722,8722,8722,8722,8722,8722,8722,8722,8722,8722,8722,8722,8722,8722,8722,8722,8722,8722

## HP 題庫

In [115]:
# 紀錄次數 = 迭代次數次(初始解)
run_time = 20 # 執行次數
problem = ["1","2"]
algorithm = "BSMASCA_V1_RL_015_25"

result_table = np.zeros([len(problem),run_time],dtype=int)

# 循環瀏覽您的 CSV 文件
for i in range(run_time):
    for j, prob in enumerate(problem):
        # output\BSMASCA2_S0\WEING\runtime_0_prob_1_algo_BSMASCA2_S0.csv
        best_df_name = f"runtime_{i}_prob_{prob}_algo_{algorithm}.csv" # 最佳解
        df_path = f"output/{algorithm}/HP/{best_df_name}" # 最佳解
        with open(df_path, 'r') as csvfile:
            text = csvfile.read() # 讀取
            match = re.search(r'(\d+\.\d+)', text).group(1)
            result_table[j,i] = float(match)

df = pd.DataFrame(result_table)
df # 結果

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,3418,3418,3418,3418,3418,3418,3418,3418,3418,3418,3418,3418,3418,3418,3418,3418,3404,3418,3418,3418
1,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186

## PB 題庫

In [106]:
# 紀錄次數 = 迭代次數次(初始解)
run_time = 20 # 執行次數
problem = ["1","2","4","5","6","7"]
algorithm = "BSMASCA_V1_RL_015_25"

result_table = np.zeros([len(problem),run_time],dtype=int)

# 循環瀏覽您的 CSV 文件
for i in range(run_time):
    for j, prob in enumerate(problem):
        # output\BSMASCA2_S0\WEING\runtime_0_prob_1_algo_BSMASCA2_S0.csv
        best_df_name = f"runtime_{i}_prob_{prob}_algo_{algorithm}.csv" # 最佳解
        df_path = f"output/{algorithm}/PB/{best_df_name}" # 最佳解
        with open(df_path, 'r') as csvfile:
            text = csvfile.read() # 讀取
            match = re.search(r'(\d+\.\d+)', text).group(1)
            result_table[j,i] = float(match)

df = pd.DataFrame(result_table)
df # 結果

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,3090,3090,3090,3090,3090,3090,3090,3090,3090,3090,3090,3090,3090,3090,3090,3090,3090,3090,3090,3090
1,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186,3186
2,95168,95168,95168,95168,95168,95168,95168,95168,95168,95168,95168,95168,95168,95168,95168,95168,95168,95168,95168,95168
3,2139,2139,2139,2139,2139,2139,2139,2139,2139,2139,2139,2139,2139,2139,2139,2139,2139,2139,2139,2139
4,776,776,776,776,776,776,776,776,776,776,776,776,776,776,776,776,776,776,776,776
5,1035,1035,1035,1035,1035,1035,1035,1035,1035,1035,1035,1035,1035,1035,1035,1035,1035,1035,1035,1035

## WEING 題庫

In [96]:
# 紀錄次數 = 迭代次數次(初始解)
run_time = 20 # 執行次數
problem = ["1","2","3","4","5","6","7","8"]
algorithm = "BSMASCA_V1_RL_015_25"

result_table = np.zeros([len(problem),run_time],dtype=int)

# 循環瀏覽您的 CSV 文件
for i in range(run_time):
    for j, prob in enumerate(problem):
        # output\BSMASCA2_S0\WEING\runtime_0_prob_1_algo_BSMASCA2_S0.csv
        best_df_name = f"runtime_{i}_prob_{prob}_algo_{algorithm}.csv" # 最佳解
        df_path = f"output/{algorithm}/WEING/{best_df_name}" # 最佳解
        with open(df_path, 'r') as csvfile:
            text = csvfile.read() # 讀取
            match = re.search(r'(\d+\.\d+)', text).group(1)
            result_table[j,i] = float(match)

df = pd.DataFrame(result_table)
df # 結果

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,141278,141278,141278,141278,141278,141278,141278,141278,141278,141278,141278,141278,141278,141278,141278,141278,141278,141278,141278,141278
1,130883,130883,130883,130883,130883,130883,130883,130883,130883,130883,130883,130883,130883,130883,130883,130883,130883,130883,130883,130883
2,95677,95677,95677,95677,95677,95677,95677,95677,95677,95677,95677,95677,95677,95677,95677,95677,95677,95677,95677,95677
3,119337,119337,119337,119337,119337,119337,119337,119337,119337,119337,119337,119337,119337,119337,119337,119337,119337,119337,119337,119337
4,98796,98796,98796,98796,98796,98796,98796,98796,98796,98796,98796,98796,98796,98796,98796,98796,98796,98796,98796,98796
5,130623,130623,130623,130623,130623,130623,130623,130623,130623,130623,130623,130623,130623,130623,130623,130623,130623,130623,130623,130623
6,1095382,1095382,1095445,1095382,1095382,1095382,1095382,1095382,1095382,1095382,1095445,1095382,1095382,1095382,1095382,1095382,1095382,1095382,1095382,1095382
7,624319,624319,624319,624319,624319,624319,624319,624319,624319,624319,624319,624319,624319,624319,624319,624319,624319,624319,624319,624319

## WEISH 題庫

In [85]:
# 紀錄次數 = 迭代次數次(初始解)
run_time = 20 # 執行次數
problem = ["01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"]
algorithm = "BSMASCA_V1_RL_015_25"

result_table = np.zeros([len(problem),run_time],dtype=int)

# 循環瀏覽您的 CSV 文件
for i in range(run_time):
    for j, prob in enumerate(problem):
        best_df_name = f"runtime_{i}_prob_{prob}_algo_{algorithm}.csv" # 最佳解
        df_path = f"output/{algorithm}/WEISH/{best_df_name}" # 最佳解
        with open(df_path, 'r') as csvfile:
            text = csvfile.read() # 讀取
            match = re.search(r'(\d+\.\d+)', text).group(1)
            result_table[j,i] = float(match)

df = pd.DataFrame(result_table)
df # 結果

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,4554,4554,4554,4554,4554,4554,4554,4554,4554,4554,4554,4554,4554,4554,4554,4554,4554,4554,4554,4554
1,4536,4536,4536,4536,4536,4536,4536,4536,4536,4536,4536,4536,4536,4536,4536,4536,4536,4536,4536,4536
2,4115,4115,4115,4115,4115,4115,4115,4115,4115,4115,4115,4115,4115,4115,4115,4115,4115,4115,4115,4115
3,4561,4561,4561,4561,4561,4561,4561,4561,4561,4561,4561,4561,4561,4561,4561,4561,4561,4561,4561,4561
4,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514
5,5557,5557,5557,5557,5557,5557,5557,5557,5557,5557,5557,5557,5557,5557,5557,5557,5557,5557,5557,5557
6,5567,5567,5567,5567,5567,5567,5567,5567,5567,5567,5567,5567,5567,5567,5567,5567,5567,5567,5567,5567
7,5605,5605,5605,5605,5605,5605,5605,5605,5605,5605,5605,5605,5605,5605,5605,5605,5605,5605,5605,5605
8,5246,5246,5246,5246,5246,5246,5246,5246,5246,5246,5246,5246,5246,5246,5246,5246,5246,5246,5246,5246
9,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339
10,5643,5643,5643,5643,5643,5643,5643,5643,5643,5643,5643,5643,5643,5643,5643,5643,5643,5643,5643,5643
11,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339,6339
12,6159,6159,6159,6159,6159,6159,6159,6159,6159,6159,6159,6159,6159,6159,6159,6159,6159,6159,6159,6159
13,6954,6954,6954,6954,6954,6954,6954,6954,6954,6954,6954,6954,6954,6954,6954,6954,6954,6954,6954,6954
14,7486,7486,7486,7486,7486,7486,7486,7486,7486,7486,7486,7486,7486,7486,7486,7486,7486,7486,7486,7486
15,7289,7289,7289,7289,7289,7289,7289,7289,7289,7289,7289,7289,7289,7289,7289,7289,7289,7289,7289,7289
16,8633,8633,8633,8633,8633,8633,8633,8633,8633,8633,8633,8633,8633,8633,8633,8633,8633,8633,8633,8633
17,9580,9580,9580,9580,9580,9580,9580,9580,9580,9580,9580,9580,9580,9580,9580,9580,9580,9580,9580,9580
18,7698,7698,7698,7698,7698,7698,7698,7698,7698,7698,7698,7698,7698,7698,7698,7698,7698,7698,7698,7698
19,9450,9450,9450,9450,9450,9450,9450,9450,9450,9450,9450,9450,9450,9450,9450,9450,9450,9450,9450,9450
20,9074,9074,9074,9074,9074,9074,9074,9074,9074,9074,9074,9074,9074,9074,9074,9074,9074,9074,9074,9074
21,8947,8947,8947,8947,8947,8947,8947,8947,8947,8947,8947,8947,8947,8947,8947,8947,8947,8947,8947,8947
22,8344,8344,8344,8344,8344,8344,8344,8344,8344,8344,8344,8344,8344,8344,8344,8344,8344,8344,8344,8344
23,10220,10220,10220,10220,10220,10220,10220,10220,10220,10220,10220,10220,10220,10220,10220,10220,10220,10220,10220,10220
24,9939,9939,9939,9939,9939,9939,9939,9939,9939,9939,9939,9939,9939,9939,9939,9939,9939,9939,9939,9939
25,9584,9584,9584,9584,9584,9584,9584,9584,9584,9584,9584,9584,9584,9584,9584,9584,9584,9584,9584,9584
26,9819,9819,9819,9819,9819,9819,9819,9819,9819,9819,9819,9819,9819,9819,9819,9819,9819,9819,9819,9819
27,9492,9492,9492,9492,9492,9492,9492,9492,9492,9492,9492,9492,9492,9492,9492,9492,9492,9492,9492,9492
28,9410,9410,9410,9410,9410,9410,9410,9410,9410,9410,9410,9410,9410,9410,9410,9410,9410,9410,9410,9410
29,11191,11191,11191,11191,11191,11191,11191,11191,11191,11191,11191,11191,11191,11191,11191,11191,11191,11191,11191,11191

## CB 題庫

In [15]:
# 紀錄次數 = 迭代次數次(初始解)
run_time = 20 # 執行次數
directory = ["OR5x100","OR5x250","OR5x500","OR10x100","OR10x250","OR10x500"]
problem = ["1","2","3","4","5"]
algorithm = "BSCA_V1_25"

result_table = np.zeros([len(problem)*len(directory),run_time],dtype=int)

# 循環瀏覽您的 CSV 文件
for j, file in enumerate(directory):
    result = np.zeros([len(problem),run_time])
    for i in range(run_time):
        for k, prob in enumerate(problem):
            
            best_df_name = f"runtime_{i}_{file}-0.25_{prob}_algo_{algorithm}.csv" # 最佳解
            df_path = f"output4/{algorithm}/cb/{file}/{best_df_name}" # 最佳解

            with open(df_path, 'r') as csvfile:

                text = csvfile.read() # 讀取
                
                if text != None:
                    match = re.search(r'(\d+\.\d+)', text).group(1)
                    result[k,i] = float(match)
                else:
                    result[k,i] = ""
    # print(result)
    result_table[j*len(problem):j*len(problem)+5] = result
        

df = pd.DataFrame(result_table)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,24343,24381,24381,24343,24343,24381,24381,24343,24381,24343,24343,24381,24381,24381,24381,24381,24381,24381,24343,24381
1,24274,24274,24274,24274,24274,24230,24274,24274,24274,24274,24274,24274,24274,24274,24274,24230,24274,24274,24274,24274
2,23538,23523,23523,23523,23523,23523,23523,23523,23523,23523,23523,23523,23523,23523,23523,23523,23523,23523,23523,23523
3,23497,23460,23484,23484,23480,23484,23501,23501,23480,23480,23460,23480,23480,23501,23480,23480,23484,23501,23501,23480
4,23939,23922,23950,23950,23991,23991,23950,23966,23950,23950,23950,23950,23950,23950,23950,23991,23950,23950,23950,23950
5,59243,59243,59203,59243,59243,59243,59243,59243,59243,59243,59312,59212,59312,59312,59243,59243,59243,59243,59243,59206
6,61416,61409,61416,61416,61416,61449,61450,61435,61416,61416,61416,61430,61416,61449,61449,61416,61307,61449,61430,61409
7,61912,62057,62019,62057,62065,62065,62025,62057,62065,62019,62025,62065,62027,62042,62057,62057,62057,62029,62029,62038
8,59389,59427,59427,59411,59425,59407,59427,59407,59380,59411,59380,59380,59378,59427,59398,59379,59408,59380,59379,59425
9,58950,58917,58950,58950,58950,58950,58917,58950,58950,58950,58950,58917,58950,58950,58950,58950,58950,58950,58950,58950
10,120087,120086,120087,120059,120087,120093,120086,120087,120086,120070,120082,120059,120093,120060,120045,120065,120065,120043,120086,120089
11,117823,117814,117823,117814,117829,117748,117814,117819,117814,117823,117814,117823,117770,117823,117814,117787,117836,117814,117814,117814
12,121027,121075,121051,121109,121096,121096,121109,121064,121071,121096,121121,121109,121109,121071,121071,121109,121109,121121,121109,121109
13,120763,120742,120763,120767,120763,120716,120762,120763,120762,120734,120702,120770,120737,120763,120763,120767,120737,120772,120770,120770
14,122237,122280,122280,122253,122289,122237,122237,122256,122272,122272,122237,122272,122280,122237,122280,122245,122256,122254,122276,122280
15,23050,23050,23050,22996,23050,23050,23050,23050,23057,23050,23050,23050,23050,23050,23050,23050,23050,23050,23057,23064
16,22750,22710,22710,22706,22801,22750,22706,22750,22750,22710,22710,22750,22750,22753,22750,22750,22750,22750,22750,22750
17,22081,22081,22066,22081,22081,22131,22081,22081,22081,22081,22066,22131,22066,22131,22066,22066,22066,22081,22131,22066
18,22699,22694,22707,22710,22710,22710,22699,22710,22699,22699,22710,22699,22699,22710,22699,22699,22710,22699,22710,22710
19,22601,22590,22528,22751,22528,22751,22751,22528,22528,22590,22528,22590,22751,22751,22528,22590,22549,22697,22528,22549
20,59121,59071,59121,59133,59076,59106,59121,59071,59076,59127,59121,59076,59121,59085,59121,59121,59106,59107,59052,59071
21,58565,58614,58637,58614,58604,58604,58604,58614,58614,58637,58574,58545,58614,58651,58574,58604,58621,58614,58606,58651
22,58034,57967,58056,58034,57960,57960,57960,58056,58034,57960,57960,57982,58034,57960,57960,57976,57966,57960,57967,57960
23,60878,60818,60937,60834,60878,60829,60878,60834,60878,60888,60878,60937,60917,60917,60878,60878,60631,60878,60834,60905
24,57965,57951,58019,57951,58019,57967,58019,57967,57951,57951,57972,57965,57967,57951,58019,58019,57951,58019,57967,58019
25,117635,117635,117635,117583,117600,117601,117615,117681,117632,117592,117648,117689,117575,117635,117635,117680,117632,117624,117692,117591
26,119082,119104,119108,119082,119082,119082,119082,119033,119083,119082,119087,119087,119082,119082,119086,119082,119087,119082,119082,119082
27,119075,119072,119050,119099,119044,119075,119053,119064,119075,119065,119024,119030,119029,119075,119054,119096,119085,119085,119053,119085
28,118708,118708,118708,118646,118708,118727,118708,118708,118727,118650,118665,118708,118741,118708,118733,118635,118708,118727,118733,118708
29,116359,116344,116267,116352,116315,116352,116330,116423,116386,116352,116378,116359,116315,116315,116423,116423,116359,116299,116298,116359

In [63]:
# 計算 PDev
def calculate_PDev(data):
    opt = [
    24381, 24274, 23551, 23534, 23991, 59312, 61472, 62130, 59463, 58951,
    120148, 117879, 121131, 120804, 122319, 23064, 22801, 22131, 22772, 22751,
    59187, 58781, 58097, 61000, 58092, 117821, 119249, 119215, 118829, 116530] # 理論最佳
    PDev = np.zeros([len(opt)])
    # print(data)
    for i,d in enumerate(data):
        PDev[i] = (opt[i] - d ) / opt[i] * 100 # 計算值
    print(data[0])
    return PDev

row_max = df.max(axis=1) # 計算平均值
row_means = df.mean(axis=1) # 計算平均值
row_min = df.min(axis=1) # 計算平均值
row_std = df.std(axis=1)
row_PDev = calculate_PDev(row_means) # PDev 值            

# print(row_max)
# 將結果存儲在新的 DataFrame 中
# 將結果合併到一個新的 DataFrame 中
static_df = pd.DataFrame({'Best': row_max, 'Mean': row_means, 'Worst':row_min,"Std":row_std,"PDev":row_PDev})
# 創建多層次索引
static_df.columns = pd.MultiIndex.from_product([[f'{algorithm}'], static_df.columns])
# 查看結果
# 沿水平軸合併兩個 DataFrame
result_df = pd.concat([result_df, static_df], axis=1)
result_df

# df = pd.DataFrame(result_table)
# df

24355.3

   BSMA_V1_015                                        BSMA_V1_001             \
          Best   Average    Worst       Std      PDev        Best       Mean
0       3766.0   3758.95   3756.0  3.051747  0.187201       24381   24352.50
1       3952.0   3948.35   3943.0  3.013566  0.243810       24274   24267.40
2       5642.0   5637.15   5630.0  2.852054  0.333274       23523   23523.00
3       5756.0   5747.75   5741.0  4.011497  0.333796       23501   23484.70
4       7552.0   7549.80   7546.0  2.142306  0.134921       23991   23932.00
5       7658.0   7652.10   7643.0  4.339537  0.324345       59312   59233.25
6      19206.0  19199.30  19191.0  3.628832  0.112897       61446   61426.25
7      18768.0  18750.30  18729.0  9.776987  0.296182       62057   62005.00
8      58069.0  58060.50  58052.0  4.882838  0.049063       59427   59398.55
9          NaN       NaN      NaN       NaN       NaN       58950   58948.40
10         NaN       NaN      NaN       NaN       NaN      120116  120056.65
11         NaN       NaN      NaN       NaN       NaN      117854  117801.80
12         NaN       NaN      NaN       NaN       NaN      121109  121067.00
13         NaN       NaN      NaN       NaN       NaN      120770  120733.85
14         NaN       NaN      NaN       NaN       NaN      122280  122252.40
15         NaN       NaN      NaN       NaN       NaN       23050   23044.60
16         NaN       NaN      NaN       NaN       NaN       22801   22744.10
17         NaN       NaN      NaN       NaN       NaN       22131   22097.15
18         NaN       NaN      NaN       NaN       NaN       22763   22706.05
19         NaN       NaN      NaN       NaN       NaN       22751   22612.60
20         NaN       NaN      NaN       NaN       NaN       59164   59079.15
21         NaN       NaN      NaN       NaN       NaN       58651   58575.00
22         NaN       NaN      NaN       NaN       NaN       58034   57971.70
23         NaN       NaN      NaN       NaN       NaN       61000   60876.45
24         NaN       NaN      NaN       NaN       NaN       58019   57965.15
25         NaN       NaN      NaN       NaN       NaN      117689  117598.15
26         NaN       NaN      NaN       NaN       NaN      119102  119083.50
27         NaN       NaN      NaN       NaN       NaN      119097  119048.85
28         NaN       NaN      NaN       NaN       NaN      118733  118680.95
29         NaN       NaN      NaN       NaN       NaN      116404  116333.20

                                                                       \
     Worst        Std      PDev    Best       Mean   Worst        Std
0    24304  26.396770  0.116894   24381   24352.50   24304  26.396770
1    24230  16.119292  0.027190   24274   24267.40   24230  16.119292
2    23523   0.000000  0.118891   23523   23523.00   23523   0.000000
3    23460  10.392811  0.209484   23501   23484.70   23460  10.392811
4    23795  59.956124  0.245926   23991   23932.00   23795  59.956124
5    59192  26.211438  0.132772   59312   59233.25   59192  26.211438
6    61409  11.968709  0.074424   61446   61426.25   61409  11.968709
7    61912  43.388090  0.201191   62057   62005.00   61912  43.388090
8    59350  23.486782  0.108387   59427   59398.55   59350  23.486782
9    58934   4.924696  0.004410   58950   58948.40   58934   4.924696
10  119845  56.777752  0.076031  120116  120056.65  119845  56.777752
11  117744  27.656921  0.065491  117854  117801.80  117744  27.656921
12  121009  27.667195  0.052835  121109  121067.00  121009  27.667195
13  120678  27.232479  0.058069  120770  120733.85  120678  27.232479
14  122169  29.092231  0.054448  122280  122252.40  122169  29.092231
15   22996  14.258515  0.084114   23050   23044.60   22996  14.258515
16   22680  36.673381  0.249550   22801   22744.10   22680  36.673381
17   22064  28.994146  0.152953   22131   22097.15   22064  28.994146
18   22627  30.834832  0.289610   22763   22706.05   22627  30.834832
19   22549  52.241746  0.608325   22751   22612.60   22549  52.241746
20   59020  34.900271  0.182219   59164   59079.15   59020  34.900271
21   58517  39.237469  0.350453   58651   58575.00   58517  39.237469
22   57851  44.636662  0.215674   58034   57971.70   57851  44.636662
23   60818  39.947960  0.202541   61000   60876.45   60818  39.947960
24   57893  32.959744  0.218361   58019   57965.15   57893  32.959744
25  117450  66.159516  0.189143  117689  117598.15  117450  66.159516
26  119082   4.616903  0.138785  119102  119083.50  119082   4.616903
27  118953  38.868571  0.139370  119097  119048.85  118953  38.868571
28  118613  49.505422  0.124591  118733  118680.95  118613  49.505422
29  116238  38.979887  0.168884  116404  116333.20  116238  38.979887

                                                             BSMA_V1_008  \
        PDev    Best       Mean   Worst        Std      PDev        Best
0   0.116894   24381   24352.50   24304  26.396770  0.116894       24381
1   0.027190   24274   24267.40   24230  16.119292  0.027190       24274
2   0.118891   23523   23523.00   23523   0.000000  0.118891       23538
3   0.209484   23501   23484.70   23460  10.392811  0.209484       23511
4   0.245926   23991   23932.00   23795  59.956124  0.245926       23991
5   0.132772   59312   59233.25   59192  26.211438  0.132772       59243
6   0.074424   61446   61426.25   61409  11.968709  0.074424       61468
7   0.201191   62057   62005.00   61912  43.388090  0.201191       62065
8   0.108387   59427   59398.55   59350  23.486782  0.108387       59427
9   0.004410   58950   58948.40   58934   4.924696  0.004410       58950
10  0.076031  120116  120056.65  119845  56.777752  0.076031      120130
11  0.065491  117854  117801.80  117744  27.656921  0.065491      117829
12  0.052835  121109  121067.00  121009  27.667195  0.052835      121109
13  0.058069  120770  120733.85  120678  27.232479  0.058069      120778
14  0.054448  122280  122252.40  122169  29.092231  0.054448      122280
15  0.084114   23050   23044.60   22996  14.258515  0.084114       23050
16  0.249550   22801   22744.10   22680  36.673381  0.249550       22801
17  0.152953   22131   22097.15   22064  28.994146  0.152953       22131
18  0.289610   22763   22706.05   22627  30.834832  0.289610       22763
19  0.608325   22751   22612.60   22549  52.241746  0.608325       22751
20  0.182219   59164   59079.15   59020  34.900271  0.182219       59133
21  0.350453   58651   58575.00   58517  39.237469  0.350453       58651
22  0.215674   58034   57971.70   57851  44.636662  0.215674       58043
23  0.202541   61000   60876.45   60818  39.947960  0.202541       60917
24  0.218361   58019   57965.15   57893  32.959744  0.218361       58060
25  0.189143  117689  117598.15  117450  66.159516  0.189143      117689
26  0.138785  119102  119083.50  119082   4.616903  0.138785      119087
27  0.139370  119097  119048.85  118953  38.868571  0.139370      119085
28  0.124591  118733  118680.95  118613  49.505422  0.124591      118775
29  0.168884  116404  116333.20  116238  38.979887  0.168884      116423

                                           BSMA_V1_015                     \
         Mean   Worst        Std      PDev        Best       Mean   Worst
0    24361.00   24314  24.155200  0.082031       24381   24355.30   24314
1    24269.60   24230  13.542914  0.018126       24274   24274.00   24274
2    23523.75   23523   3.354102  0.115706       23538   23527.30   23523
3    23487.90   23460  11.620762  0.195887       23534   23486.80   23436
4    23943.90   23795  38.608562  0.196324       23991   23954.70   23889
5    59212.65   59160  26.852962  0.167504       59243   59225.35   59160
6    61429.25   61409  17.109170  0.069544       61468   61427.90   61409
7    62028.40   61912  31.789439  0.163528       62065   62027.85   61912
8    59394.35   59364  22.523146  0.115450       59429   59400.60   59360
9    58940.70   58909  14.513515  0.017472       58950   58930.45   58874
10  120074.75  120004  34.467185  0.060966      120130  120062.15  119992
11  117799.60  117738  27.591761  0.067357      117835  117781.25  117716
12  121065.80  121005  30.062391  0.053826      121121  121059.55  121000
13  120735.70  120677  27.551101  0.056538      120785  120734.80  120633
14  122252.40  122185  32.397856  0.054448      122319  122263.65  122205
15   23041.90   22969  21.326781  0.095820       23064   23043.15   22996
16   22756.70   22699  37.918333  0.194290       22801   22756.20   22693
17   22094.65   22064  28.062477  0.164249       22131   22082.30   22064
18   22707.95   22639  27.965157  0.281266       22772   22724.20   22669
19   22617.30   22590  45.997826  0.587666       22697   22607.40   22549
20   59077.30   59011  41.457778  0.185345       59133   59073.60   58993
21   58580.35   58534  39.696579  0.341352       58637   58567.10   58486
22   57982.50   57869  42.739726  0.197084       57995   57961.80   57895
23   60858.05   60703  46.776597  0.232705       61000   60863.35   60703
24   57971.50   57865  42.376135  0.207430       58060   57950.75   57877
25  117596.85  117454  70.343724  0.190246      117635  117562.15  117501
26  119066.80  118895  47.018026  0.152790      119114  119054.95  118923
27  119008.40  118714  81.955315  0.173300      119085  119012.90  118866
28  118662.20  118616  41.991979  0.140370      118727  118663.95  118573
29  116351.50  116199  62.577531  0.153179      116423  116334.75  116218


          Std      PDev
0   23.179165  0.105410
1    0.000000  0.000000
2    6.790861  0.100633
3   20.702403  0.200561
4   22.178937  0.151307
5   26.547425  0.146092
6   18.275379  0.071740
7   32.496599  0.164413
8   21.315673  0.104939
9   21.283735  0.034859
10  35.211055  0.071454
11  39.858797  0.082924
12  37.079538  0.058986
13  38.092132  0.057283
14  30.899285  0.045251
15  18.991064  0.090401
16  39.140234  0.196483
17  22.235817  0.220053
18  33.725830  0.209907
19  29.750542  0.631181
20  41.343745  0.191596
21  41.555163  0.363893
22  24.960179  0.232714
23  55.156500  0.224016
24  42.219819  0.243149
25  41.852215  0.219698
26  50.880122  0.162727
27  58.630780  0.169526
28  53.254577  0.138897
29  59.364951  0.167553

## GK 題庫

In [2]:
# 計算 PDev
def calculate_PDev(data):
    opt = [3766,3958,5656,5767,7560,7677,19221,18806,58089] # 理論最佳
    PDev = np.zeros([len(opt)])
    # print(data)
    for i,d in enumerate(data):
        PDev[i] = (opt[i] - d ) / opt[i] * 100 # 計算值
    print(data[0])
    return PDev

# 紀錄次數 = 迭代次數次(初始解)
run_time = 20 # 執行次數
problem = ["01","02","03","04","05","06","07","08","09"]
algorithm = "BSMA_V1_008"

result_table = np.zeros([len(problem),run_time],dtype=int)
result_df = pd.DataFrame()
# 循環瀏覽您的 CSV 文件
for i in range(run_time):
    for j, prob in enumerate(problem):
        best_df_name = f"runtime_{i}_prob_{prob}_algo_{algorithm}.csv" # 最佳解
        df_path = f"output3/{algorithm}/GK/{best_df_name}" # 最佳解
        with open(df_path, 'r') as csvfile:
            text = csvfile.read() # 讀取
            if text != None:
                match = re.search(r'(\d+\.\d+)', text).group(1)
                result_table[j,i] = float(match)
            else:
                result_table[j,i] = ""

# 顯示數據細節
df = pd.DataFrame(result_table)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,3759,3766,3766,3766,3755,3766,3759,3756,3756,3759,3766,3766,3766,3756,3766,3766,3756,3766,3759,3766
1,3949,3952,3952,3949,3949,3949,3949,3952,3949,3949,3952,3951,3952,3952,3952,3951,3952,3946,3952,3949
2,5640,5640,5641,5639,5645,5641,5640,5643,5644,5633,5640,5637,5633,5640,5641,5640,5642,5633,5631,5634
3,5752,5760,5750,5756,5753,5760,5760,5754,5743,5755,5755,5753,5758,5750,5746,5758,5749,5754,5751,5752
4,7549,7546,7550,7552,7546,7552,7555,7552,7550,7552,7549,7550,7552,7550,7549,7550,7553,7555,7552,7552
5,7659,7660,7658,7665,7661,7657,7657,7661,7664,7659,7659,7661,7649,7654,7654,7661,7659,7665,7665,7665
6,19196,19200,19202,19200,19201,19210,19201,19203,19201,19199,19201,19195,19199,19205,19197,19210,19199,19196,19198,19202
7,18778,18767,18771,18780,18774,18765,18768,18772,18766,18770,18763,18768,18767,18773,18766,18780,18772,18775,18768,18771
8,58069,58057,58064,58069,58064,58061,58060,58058,58071,58066,58067,58069,58064,58059,58067,58063,58068,58064,58065,58060

# 彙總

In [41]:
row_max = df.max(axis=1) # 計算平均值
row_means = df.mean(axis=1) # 計算平均值
row_min = df.min(axis=1) # 計算平均值
row_std = df.std(axis=1)
row_PDev = calculate_PDev(row_means) # PDev 值            

# print(row_max)
# 將結果存儲在新的 DataFrame 中
# 將結果合併到一個新的 DataFrame 中
static_df = pd.DataFrame({'Best': row_max, 'Mean': row_means, 'Worst':row_min,"Std":row_std,"PDev":row_PDev})
# 創建多層次索引
static_df.columns = pd.MultiIndex.from_product([[f'{algorithm}'], static_df.columns])
# 查看結果
# 沿水平軸合併兩個 DataFrame
result_df = pd.concat([result_df, static_df], axis=1)
result_df

# df = pd.DataFrame(result_table)
# df

3757.95

  BSMASCA2_V1_008_25_060
                    Best      Mean  Worst       Std      PDev
0                   3766   3757.95   3753  2.645254  0.213755
1                   3955   3948.90   3935  4.552616  0.229914
2                   5650   5642.70   5634  4.508472  0.235149
3                   5754   5746.50   5739  3.561490  0.355471
4                   7558   7550.65   7547  2.996050  0.123677
5                   7663   7650.95   7644  4.740364  0.339325
6                  19213  19202.15  19192  4.944694  0.098070
7                  18787  18777.00  18765  5.638215  0.154206
8                  58074  58065.85  58051  6.627495  0.039853

# 威爾斯

In [ ]:
import numpy as np
from scipy.stats import wilcoxon

# 假設這些數據是某種治療前後的血壓讀數
data_before = np.array([120, 125, 130, 140, 145, 150, 135, 160, 140, 155])
data_after = np.array([115, 123, 130, 138, 140, 148, 130, 155, 135, 150])

# 計算差異
data_diff = data_after - data_before

# 執行 Wilcoxon Signed-Rank Test
w_statistic, p_value = wilcoxon(data_diff)

print(f"Wilcoxon test statistic: {w_statistic}")
print(f"P-value: {p_value}")

# 判斷結果
if p_value < 0.05:
    print("There is a significant difference between the two conditions.")
else:
    print("There is no significant difference between the two conditions.")

In [145]:

print(range(10,17))

range(10, 17)