In [23]:
import numpy as np
import pandas as pd
from initial_main1 import main
import random
import os
from initial import initial1,initial2,initial3,initial3_1,initial3_3

# 设置 Pandas 显示选项，以便显示所有行和列
pd.set_option('display.max_rows', None)  # 显示所有行
pd.set_option('display.max_columns', None)  # 显示所有列

log_pop_size = main.pop_size # 種群大小
log_5d = 5 # 維度
# 紀錄次數 = 迭代次數次(初始解)
run_time = main.run_time # 執行次數
problem_time = main.problem1 # 問題是prob = [01,02,...,30]
# r_para = main.r2
algorithm_select = main.algorithm_select

print(algorithm_select)

['initial1', 'initial2', 'initial3', 'initial3_1', 'initial3_3']

1. **輪盤法（Roulette Wheel Selection）**：這是最經典的選擇方法之一，個體被選擇的概率與其適應度成正比。在輪盤法中，適應度高的個體更有可能被選中。

2. **錦標賽選擇（Tournament Selection）**：這種方法將個體隨機分成小組（錦標賽），每個小組中的個體相互競爭，適應度最高的個體獲勝並被選中。

3. **隨機選擇（Random Selection）**：這是一種簡單的方法，每個個體都有相等的機會被選中，不考慮其適應度。

4. **比例選擇（Proportional Selection）**：與輪盤法類似，但不是完全按適應度選擇。個體的適應度值被歸一化，並且在選擇時根據歸一化的適應度值來選擇個體。

5. **指數選擇（Exponential Selection）**：適應度高的個體獲得更高的概率被選擇，但相對於輪盤法，適應度差異更明顯。

6. **排名選擇（Rank Selection）**：個體根據其適應度排名來選擇，排名高的個體獲得更高的選擇概率。

7. **剪枝選擇（Stochastic Universal Sampling）**：與輪盤法類似，但使用均勻分佈來選擇個體，以減少隨機性。

8. **自適應選擇（Adaptive Selection）**：根據進化過程中個體的適應度動態調整選擇概率，以更好地適應搜索空間。

這些方法在不同情況下表現不同，通常需要根據具體問題和算法的性質來選擇合適的選擇方法。輪盤法是最常用的方法之一，但其他方法也在特定情況下具有優勢。

# 0. 初始解分析
分析算法生成的解（solution）和它們的適應值（fitness）是非常重要的，它可以幫助你了解算法的性能，進行改進和優化。以下是一些分析解的方法：

1. **適應度分佈分析**：繪製適應度值的直方圖或箱線圖，以了解解決方案的分佈情況。這有助於確定是否存在局部最優解或離群值。

2. **最佳解**：確定最佳解的適應度和特徵，以及它們在迭代過程中的變化。這有助於了解算法是否在不斷改進解。

3. **收斂分析**：跟踪算法的收斂情況，即適應度是否趨於穩定。你可以繪製適應度隨時間或迭代次數的變化圖表。

4. **參數敏感性分析**：改變算法的參數（如果有的話），觀察它們對解和適應值的影響。這有助於優化參數選擇。

5. **統計分析**：使用統計方法對解決方案的性能進行分析，如均值、方差、標準差等。這可以提供有關解性能的數值摘要。

6. **對比實驗**：與其他算法或不同參數設置的算法進行對比，以確定哪種方法在解決特定問題上表現最好。

7.  **可解釋性分析**：如果可能的話，解釋模型或算法生成的解，以理解為什麼某些解更優越。

## 這次資料分析的工作項目

* 動態變數跑批次檔
* 每個個體在迭代過程的狀態(解，適應值)輸出到.csv[X]
* 會有排序問題，要重新整理成可追蹤模式[X]
* 要分成幾個 df 分別儲存第 n 次迭代的資料[X]
* 印出點陣圖檢查有沒有過早收斂(檢查每次迭代適應值的標準差) => 繪製標準差收斂曲線[]
* 輸出位置更新的狀態，檢查有無重複移動[]
* 更新 cp 值公式[]
* 紀錄算法運行時間[X]
* 紀錄可行解與不可行解的數量[X]

* 現在初始解中不可行的初始解太高導致必須要靠修復函數進而導致種群多樣性不足[]
* 思考CP 值公式的優化[]

* 種群在迭代過程的收斂狀態，針對適應值
* 評估種群決策多樣性(找找看多樣性有沒有什麼統計分析)
* 整理每個個體在位置更新時移動軌跡(決策變動的過程)

In [24]:
log_df = {} # 紀錄運行過程
best_df = {} # 紀錄最佳解
# 批次讀取 CSV 文件，動態生成變量
for i in range(run_time):
    for prob in main.problem1:
        for name in algorithm_select:
            log_df[f"log_run_{i}_prob_{prob}_algorithm_{name}"] = pd.read_csv(f"output/{name}/log_runtime_{i}_problem_{prob}_algorithm_{name}.csv") # 更新紀錄
            best_df[f"best_run_{i}_prob_{prob}_algorithm_{name}"] = pd.read_csv(f"output/{name}/best_runtime_{i}_problem_{prob}_algorithm_{name}.csv") # 最佳解
            # 名稱
            log_df[f"log_run_{i}_prob_{prob}_algorithm_{name}"].rename(columns = {log_df[f"log_run_{i}_prob_{prob}_algorithm_{name}"].columns[0]:"編號"}, inplace = True) # 改變欄位名稱
            log_df[f"log_run_{i}_prob_{prob}_algorithm_{name}"].rename(columns = {log_df[f"log_run_{i}_prob_{prob}_algorithm_{name}"].columns[-1]:"適應值"}, inplace = True) # 改變欄位名稱
            best_df[f"best_run_{i}_prob_{prob}_algorithm_{name}"].rename(columns = {best_df[f"best_run_{i}_prob_{prob}_algorithm_{name}"].columns[0]:"編號"}, inplace = True) # 改變欄位名稱
            best_df[f"best_run_{i}_prob_{prob}_algorithm_{name}"].rename(columns = {best_df[f"best_run_{i}_prob_{prob}_algorithm_{name}"].columns[-1]:"適應值"}, inplace = True) # 改變欄位名稱
            # 數值轉換
            log_df[f"log_run_{i}_prob_{prob}_algorithm_{name}"] = log_df[f"log_run_{i}_prob_{prob}_algorithm_{name}"].astype(float).round(1) # 轉換
            best_df[f"best_run_{i}_prob_{prob}_algorithm_{name}"] = best_df[f"best_run_{i}_prob_{prob}_algorithm_{name}"].astype(float).round(1) # 轉換

In [30]:
# 顯示資料
log_df["log_run_0_prob_01_algorithm_initial1"].head(20) # 顯示資料
# log_df["log_run_0"].columns[0] # 列名

,編號,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,適應值
0,0.2,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,-424.0
1,0.2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,-451.0
2,0.2,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,-455.0
3,0.2,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,-477.0
4,0.2,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,-508.0
5,0.2,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,-529.0
6,0.2,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,-556.0
7,0.2,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,-588.0
8,0.2,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,-594.0
9,0.2,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,-601.0
10,0.2,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,-603.0
11,0.2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,-603.0
12,0.2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,-607.0
13,0.2,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,-611.0
14,0.2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,-642.0
15,0.2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,-642.0
16,0.2,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,-664.0
17,0.2,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,-665.0
18,0.2,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,-665.0
19,0.2,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,-720.0

# initial 3 輪盤法+ 貪婪法

In [31]:
# 顯示資料
log_df["log_run_0_prob_01_algorithm_initial3"].head(20) # 顯示資料

,編號,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,適應值
0,15.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1496.0
1,5.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1436.0
2,8.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1261.0
3,10.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1108.0
4,14.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1106.0
5,20.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1045.0
6,12.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1017.0
7,7.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,925.0
8,19.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,834.0
9,6.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,814.0
10,3.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,757.0
11,17.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,729.0
12,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,708.0
13,16.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,705.0
14,11.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,641.0
15,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,618.0
16,9.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,616.0
17,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,530.0
18,13.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,481.0
19,18.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,397.0

# initial 3_1 輪盤法+ 貪婪法

In [32]:
# 顯示資料
log_df["log_run_0_prob_01_algorithm_initial3_1"].head(20) # 顯示資料

,編號,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,適應值
0,13.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1728.0
1,10.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1547.0
2,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1154.0
3,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1119.0
4,16.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1116.0
5,3.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1108.0
6,12.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1107.0
7,4.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1050.0
8,17.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,921.0
9,11.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,905.0
10,18.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,878.0
11,19.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,820.0
12,8.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,752.0
13,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,668.0
14,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,663.0
15,15.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,652.0
16,6.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,642.0
17,9.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,636.0
18,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,598.0
19,5.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,528.0

# 3_2 輪盤法+貪婪

In [33]:
# 顯示資料
log_df["log_run_1_prob_01_algorithm_initial3_3"].head(20) # 顯示資料

,編號,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,適應值
0,20.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1540.0
1,12.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1336.0
2,16.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1335.0
3,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1287.0
4,8.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1270.0
5,2.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1232.0
6,9.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1057.0
7,17.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1040.0
8,3.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1004.0
9,11.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,994.0
10,19.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,869.0
11,13.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,786.0
12,14.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,709.0
13,7.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,665.0
14,15.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,573.0
15,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,571.0
16,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,481.0
17,4.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,477.0
18,10.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,418.0
19,5.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,367.0

In [34]:
total=log_df["log_run_10_prob_01_algorithm_initial3"].iloc[:,-1].values
print(total)
sum = np.sum(total)
sum

KeyError: 'log_run_10_prob_01_algorithm_initial3'

# 1.隨機生成初始解

In [ ]:
# 顯示資料
log_df["log_run_0_prob_01_algorithm_initial1"].head(20) # 顯示資料
# log_df["log_run_0"].columns[0] # 列名

,編號,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,適應值
0,3.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1125.0
1,15.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,909.0
2,10.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,880.0
3,13.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,843.0
4,14.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,671.0
5,8.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,602.0
6,18.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,551.0
7,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,508.0
8,16.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-15.0
9,9.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-23.0
10,4.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,-36.0
11,12.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,-46.0
12,17.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,-55.0
13,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,-58.0
14,19.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,-69.0
15,6.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,-98.0
16,5.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-106.0
17,7.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,-114.0
18,11.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,-184.0
19,2.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,-258.0

In [ ]:
total=log_df["log_run_7_prob_01_algorithm_initial3_3"].iloc[:,-1].values
print(total)
sum = np.sum(total)
sum

[1865. 1366. 1242. 1193. 1155. 1048. 1005. 1003.  993.  876.  861.  780.
  733.  697.  692.  619.  548.  536.  523.  452.]

18187.0

# 1.初始解分析
每個決策變數生成的步驟:
* 利用亂數產生一個界於"下界" 與 "上界" 的隨機值(r_i)
* 該隨機值(r_i)透過"轉換函數" 做映射至 0 到 1 之間的值(m_i)
* 二元化該值，如果該值 (m_i) 大於某值(r) 為 1，否則為 0

問題:
* 對於該決策變數最終產生決策與問題本身毫無關係
* 以個體的角度而言，沒有考慮限制條件(為難的點是如果全部考慮限制條件會變貪婪策略，會導致種群多樣性降低造成局部陷阱產生)
* 以種群的角度而言，不可行解太多了
目標:
* 提升種群整體的適應值
* 降低不可行解的個體數量

猜想:
* 可能可以用"輪盤法"產生初始解每一個決策變數將會受到物品的客觀條件影響
* 利用調整機率的方法使種群分布決策變數為 1 的情況合理

1. **輪盤法（Roulette Wheel Selection）**：這是最經典的選擇方法之一，個體被選擇的概率與其適應度成正比。在輪盤法中，適應度高的個體更有可能被選中。

2. **錦標賽選擇（Tournament Selection）**：這種方法將個體隨機分成小組（錦標賽），每個小組中的個體相互競爭，適應度最高的個體獲勝並被選中。

3. **隨機選擇（Random Selection）**：這是一種簡單的方法，每個個體都有相等的機會被選中，不考慮其適應度。

4. **比例選擇（Proportional Selection）**：與輪盤法類似，但不是完全按適應度選擇。個體的適應度值被歸一化，並且在選擇時根據歸一化的適應度值來選擇個體。

5. **指數選擇（Exponential Selection）**：適應度高的個體獲得更高的概率被選擇，但相對於輪盤法，適應度差異更明顯。

6. **排名選擇（Rank Selection）**：個體根據其適應度排名來選擇，排名高的個體獲得更高的選擇概率。

7. **剪枝選擇（Stochastic Universal Sampling）**：與輪盤法類似，但使用均勻分佈來選擇個體，以減少隨機性。

8. **自適應選擇（Adaptive Selection）**：根據進化過程中個體的適應度動態調整選擇概率，以更好地適應搜索空間。

這些方法在不同情況下表現不同，通常需要根據具體問題和算法的性質來選擇合適的選擇方法。輪盤法是最常用的方法之一，但其他方法也在特定情況下具有優勢。

在啟發式算法中，生成初始解（或種子解）的方法取決於問題的性質和算法的需求。以下是一些常見的生成初始解的方法：

1. **隨機生成**：這是最簡單的方法之一，通過隨機選擇問題域中的值來生成初始解。雖然簡單，但通常效果較差，適用於問題的搜索空間較小時。

2. **貪婪法（Greedy Initialization）**：根據某種啟發式規則，從問題的初始狀態開始逐步構建解。例如，對於旅行商問題（TSP），可以從一個隨機城市開始，然後選擇距離最近的未訪問城市，逐步構建巡迴路線。

3. **構造性啟發式（Constructive Heuristics）**：這些方法基於問題的結構，以一種啟發式的方式逐步構建解決方案。例如，對於背包問題，可以使用動態規劃或貪婪算法來構建解。

4. **局部搜索**：使用一種局部搜索方法（如爬山法）從一個初始解開始，嘗試改進解決方案。這通常需要一個初始解作為起點。

5. **遺傳算法的初始化**：在遺傳算法中，可以使用隨機生成一組個體作為初始種群，或者根據問題的特性生成一組個體。

6. **基於歷史信息的方法**：有些問題的初始解可以根據問題的歷史信息或已知的啟發式信息來生成。

7. **問題特定的初始化方法**：針對特定問題，可以根據問題的特性設計專門的初始化方法。例如，對於調度問題，可以根據工件的特性生成初始調度。

選擇哪種方法取決於問題的性質、算法的要求以及計算資源的可用性。通常，生成高質量的初始解對於啟發式算法的性能至關重要，因為良好的初始解可以加速算法的收斂。

In [35]:
# 批次抓初始解 第{i}次執行，第{j}個問題
initial_log = {}
for i in range(run_time):
    for j in main.problem1:
        for k in range(len(initial1.r2)):
            initial_log[f"initial1_log_run_{i}_prob_{j}_r2_{k}"] = log_df[f"log_run_{i}_prob_{j}_algorithm_initial1"].iloc[20*k:20*k+20] # initial_log[變數名稱] = 內容

In [47]:
# 顯示   
initial_log["initial1_log_run_0_prob_01_r2_3"].head(20) # 訪問動態生成的變量值(输出)
# initial_log["initial_log_run_1_prob_0"] # 訪問動態生成的變量值(输出)
# initial_log["initial_log_run_2_prob_0"] # 訪問動態生成的變量值(输出)

,編號,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,適應值
60,0.5,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1588.0
61,0.5,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,-23.0
62,0.5,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,-101.0
63,0.5,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,-135.0
64,0.5,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,-138.0
65,0.5,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,-158.0
66,0.5,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-210.0
67,0.5,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,-222.0
68,0.5,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-229.0
69,0.5,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,-234.0
70,0.5,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,-243.0
71,0.5,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,-243.0
72,0.5,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,-269.0
73,0.5,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,-284.0
74,0.5,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,-287.0
75,0.5,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-288.0
76,0.5,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,-323.0
77,0.5,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,-381.0
78,0.5,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,-384.0
79,0.5,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,-422.0

In [ ]:
# 第 i 次執行中 0 或 1 的統計數量
# log_df["log_run_0_prob_01_algorithm_initial1"]
fessible_log = {} # 紀錄空間
for i in range(run_time):
    for j in main.problem1:

            # subset = initial_log[f"initial3_log_run_{i}_prob_{j}_r2_{k}"].iloc[:, 1:-1] # 初始解的決策變數
            subset = log_df[f"log_run_{i}_prob_{j}_algorithm_initial3_3"].iloc[:, 1:-1] # 初始解的決策變數
            counts_1 = (subset.values == 1).sum() # 計算是 1 的數量
            counts_0 = (subset.values == 0).sum() # 計算是 0 的數量



            fitness = log_df[f"log_run_{i}_prob_{j}_algorithm_initial3_3"].iloc[:,-1].values
            tatal_fit = np.sum(fitness)
            # print(fitness)
            fessible = 0 # 可行
            infessible = 0 # 不可行
            for l in range(log_pop_size):
                if fitness[l] < 0 :
                    infessible += 1
                else:
                    fessible += 1
            fessible_log[f"run_{i}_prob_{j}_algorithm_initial3_3"] =  [f"log_run_{i}\t prob_{j}\t algorithm_initial3 \t 不可行\t{infessible} \t 可行 \t{fessible} \t 種群總fit \t {int(tatal_fit)}\t'1'個數 \t {counts_1}\t '0'個數 \t{counts_0}"]
            print(f"run_{i},prob_{j},algorithm_initial3_3,不可行,{infessible},可行,{fessible},種群總fit,{int(tatal_fit)},'1'個數,{counts_1},'0'個數,{counts_0}")

run_0,prob_01,algorithm_initial3_3,不可行,0,可行,20,種群總fit,20814,'1'個數,182,'0'個數,418
run_0,prob_02,algorithm_initial3_3,不可行,0,可行,20,種群總fit,19370,'1'個數,185,'0'個數,415
run_0,prob_03,algorithm_initial3_3,不可行,0,可行,20,種群總fit,12459,'1'個數,122,'0'個數,478
run_0,prob_04,algorithm_initial3_3,不可行,0,可行,20,種群總fit,8768,'1'個數,96,'0'個數,504
run_0,prob_05,algorithm_initial3_3,不可行,0,可行,20,種群總fit,6745,'1'個數,78,'0'個數,522
run_0,prob_06,algorithm_initial3_3,不可行,0,可行,20,種群總fit,22297,'1'個數,248,'0'個數,552
run_0,prob_07,algorithm_initial3_3,不可行,0,可行,20,種群總fit,19816,'1'個數,241,'0'個數,559
run_0,prob_08,algorithm_initial3_3,不可行,0,可行,20,種群總fit,22267,'1'個數,248,'0'個數,552
run_0,prob_09,algorithm_initial3_3,不可行,0,可行,20,種群總fit,11498,'1'個數,138,'0'個數,662
run_0,prob_10,algorithm_initial3_3,不可行,0,可行,20,種群總fit,15096,'1'個數,177,'0'個數,823
run_0,prob_11,algorithm_initial3_3,不可行,0,可行,20,種群總fit,9119,'1'個數,112,'0'個數,888
run_0,prob_12,algorithm_initial3_3,不可行,0,可行,20,種群總fit,14227,'1'個數,174,'0'個數,826
run_0,prob_13,algorithm_initial3_3,不可行,0,可行,20,種群總fit,13500,'1'個數,163,'0'個數,837
run_0,prob_14,algorithm_initial3_3,不可行,0,可行,20,種群總fit,17961,'1'個數,216,'0'個數,984
run_0,prob_15,algorithm_initial3_3,不可行,0,可行,20,種群總fit,12542,'1'個數,173,'0'個數,1027
run_0,prob_16,algorithm_initial3_3,不可行,0,可行,20,種群總fit,23945,'1'個數,278,'0'個數,922
run_0,prob_17,algorithm_initial3_3,不可行,0,可行,20,種群總fit,41099,'1'個數,498,'0'個數,702
run_0,prob_18,algorithm_initial3_3,不可行,0,可行,20,種群總fit,41082,'1'個數,458,'0'個數,942
run_0,prob_19,algorithm_initial3_3,不可行,0,可行,20,種群總fit,19782,'1'個數,247,'0'個數,1153
run_0,prob_20,algorithm_initial3_3,不可行,0,可行,20,種群總fit,24011,'1'個數,299,'0'個數,1101
run_0,prob_21,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21453,'1'個數,255,'0'個數,1145
run_0,prob_22,algorithm_initial3_3,不可行,0,可行,20,種群總fit,29820,'1'個數,347,'0'個數,1253
run_0,prob_23,algorithm_initial3_3,不可行,0,可行,20,種群總fit,22774,'1'個數,284,'0'個數,1316
run_0,prob_24,algorithm_initial3_3,不可行,0,可行,20,種群總fit,47554,'1'個數,545,'0'個數,1055
run_0,prob_25,algorithm_initial3_3,不可行,0,可行,20,種群總fit,28584,'1'個數,357,'0'個數,1243
run_0,prob_26,algorithm_initial3_3,不可行,0,可行,20,種群總fit,28772,'1'個數,344,'0'個數,1456
run_0,prob_27,algorithm_initial3_3,不可行,0,可行,20,種群總fit,31657,'1'個數,369,'0'個數,1431
run_0,prob_28,algorithm_initial3_3,不可行,0,可行,20,種群總fit,28528,'1'個數,319,'0'個數,1481
run_0,prob_29,algorithm_initial3_3,不可行,0,可行,20,種群總fit,24538,'1'個數,318,'0'個數,1482
run_0,prob_30,algorithm_initial3_3,不可行,0,可行,20,種群總fit,40047,'1'個數,496,'0'個數,1304
run_1,prob_01,algorithm_initial3_3,不可行,0,可行,20,種群總fit,18011,'1'個數,178,'0'個數,422
run_1,prob_02,algorithm_initial3_3,不可行,0,可行,20,種群總fit,19261,'1'個數,172,'0'個數,428
run_1,prob_03,algorithm_initial3_3,不可行,0,可行,20,種群總fit,9977,'1'個數,108,'0'個數,492
run_1,prob_04,algorithm_initial3_3,不可行,0,可行,20,種群總fit,8974,'1'個數,100,'0'個數,500
run_1,prob_05,algorithm_initial3_3,不可行,0,可行,20,種群總fit,8070,'1'個數,87,'0'個數,513
run_1,prob_06,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21660,'1'個數,260,'0'個數,540
run_1,prob_07,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21068,'1'個數,237,'0'個數,563
run_1,prob_08,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21135,'1'個數,249,'0'個數,551
run_1,prob_09,algorithm_initial3_3,不可行,0,可行,20,種群總fit,12193,'1'個數,145,'0'個數,655
run_1,prob_10,algorithm_initial3_3,不可行,0,可行,20,種群總fit,16474,'1'個數,175,'0'個數,825
run_1,prob_11,algorithm_initial3_3,不可行,0,可行,20,種群總fit,9625,'1'個數,121,'0'個數,879
run_1,prob_12,algorithm_initial3_3,不可行,0,可行,20,種群總fit,12850,'1'個數,162,'0'個數,838
run_1,prob_13,algorithm_initial3_3,不可行,0,可行,20,種群總fit,12687,'1'個數,151,'0'個數,849
run_1,prob_14,algorithm_initial3_3,不可行,0,可行,20,種群總fit,19531,'1'個數,220,'0'個數,980
run_1,prob_15,algorithm_initial3_3,不可行,0,可行,20,種群總fit,15254,'1'個數,181,'0'個數,1019
run_1,prob_16,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21361,'1'個數,260,'0'個數,940
run_1,prob_17,algorithm_initial3_3,不可行,0,可行,20,種群總fit,44492,'1'個數,499,'0'個數,701
run_1,prob_18,algorithm_initial3_3,不可行,0,可行,20,種群總fit,42824,'1'個數,493,'0'個數,907
run_1,prob_19,algorithm_initial3_3,不可行,0,可行,20,種群總fit,20616,'1'個數,232,'0'個數,1168
run_1,prob_20,algorithm_initial3_3,不可行,0,可行,20,種群總fit,29057,'1'個數,327,'0'個數,1073
run_1,prob_21,algorithm_initial3_3,不可行,0,可行,20,種群總fit,26007,'1'個數,277,'0'個數,1123
run_1,prob_22,algorithm_initial3_3,不可行,0,可行,20,種群總fit,29361,'1'個數,357,'0'個數,1243
run_1,prob_23,algorithm_initial3_3,不可行,0,可行,20,種群總fit,23699,'1'個數,288,'0'個數,1312
run_1,prob_24,algorithm_initial3_3,不可行,0,可行,20,種群總fit,44250,'1'個數,536,'0'個數,1064
run_1,prob_25,algorithm_initial3_3,不可行,0,可行,20,種群總fit,28554,'1'個數,361,'0'個數,1239
run_1,prob_26,algorithm_initial3_3,不可行,0,可行,20,種群總fit,30140,'1'個數,334,'0'個數,1466
run_1,prob_27,algorithm_initial3_3,不可行,0,可行,20,種群總fit,32335,'1'個數,366,'0'個數,1434
run_1,prob_28,algorithm_initial3_3,不可行,0,可行,20,種群總fit,26809,'1'個數,332,'0'個數,1468
run_1,prob_29,algorithm_initial3_3,不可行,0,可行,20,種群總fit,27131,'1'個數,325,'0'個數,1475
run_1,prob_30,algorithm_initial3_3,不可行,0,可行,20,種群總fit,41410,'1'個數,518,'0'個數,1282
run_2,prob_01,algorithm_initial3_3,不可行,0,可行,20,種群總fit,17243,'1'個數,178,'0'個數,422
run_2,prob_02,algorithm_initial3_3,不可行,0,可行,20,種群總fit,16905,'1'個數,169,'0'個數,431
run_2,prob_03,algorithm_initial3_3,不可行,0,可行,20,種群總fit,11842,'1'個數,116,'0'個數,484
run_2,prob_04,algorithm_initial3_3,不可行,0,可行,20,種群總fit,11782,'1'個數,114,'0'個數,486
run_2,prob_05,algorithm_initial3_3,不可行,0,可行,20,種群總fit,9132,'1'個數,90,'0'個數,510
run_2,prob_06,algorithm_initial3_3,不可行,0,可行,20,種群總fit,20880,'1'個數,247,'0'個數,553
run_2,prob_07,algorithm_initial3_3,不可行,0,可行,20,種群總fit,20196,'1'個數,230,'0'個數,570
run_2,prob_08,algorithm_initial3_3,不可行,0,可行,20,種群總fit,22660,'1'個數,258,'0'個數,542
run_2,prob_09,algorithm_initial3_3,不可行,0,可行,20,種群總fit,13232,'1'個數,161,'0'個數,639
run_2,prob_10,algorithm_initial3_3,不可行,0,可行,20,種群總fit,12005,'1'個數,170,'0'個數,830
run_2,prob_11,algorithm_initial3_3,不可行,0,可行,20,種群總fit,9532,'1'個數,109,'0'個數,891
run_2,prob_12,algorithm_initial3_3,不可行,0,可行,20,種群總fit,15986,'1'個數,171,'0'個數,829
run_2,prob_13,algorithm_initial3_3,不可行,0,可行,20,種群總fit,11597,'1'個數,147,'0'個數,853
run_2,prob_14,algorithm_initial3_3,不可行,0,可行,20,種群總fit,18908,'1'個數,207,'0'個數,993
run_2,prob_15,algorithm_initial3_3,不可行,0,可行,20,種群總fit,12595,'1'個數,166,'0'個數,1034
run_2,prob_16,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21800,'1'個數,272,'0'個數,928
run_2,prob_17,algorithm_initial3_3,不可行,0,可行,20,種群總fit,45289,'1'個數,517,'0'個數,683
run_2,prob_18,algorithm_initial3_3,不可行,0,可行,20,種群總fit,40541,'1'個數,463,'0'個數,937
run_2,prob_19,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21014,'1'個數,261,'0'個數,1139
run_2,prob_20,algorithm_initial3_3,不可行,0,可行,20,種群總fit,22504,'1'個數,292,'0'個數,1108
run_2,prob_21,algorithm_initial3_3,不可行,0,可行,20,種群總fit,22146,'1'個數,265,'0'個數,1135
run_2,prob_22,algorithm_initial3_3,不可行,0,可行,20,種群總fit,29471,'1'個數,352,'0'個數,1248
run_2,prob_23,algorithm_initial3_3,不可行,0,可行,20,種群總fit,25127,'1'個數,282,'0'個數,1318
run_2,prob_24,algorithm_initial3_3,不可行,0,可行,20,種群總fit,45312,'1'個數,538,'0'個數,1062
run_2,prob_25,algorithm_initial3_3,不可行,0,可行,20,種群總fit,30322,'1'個數,376,'0'個數,1224
run_2,prob_26,algorithm_initial3_3,不可行,0,可行,20,種群總fit,25858,'1'個數,347,'0'個數,1453
run_2,prob_27,algorithm_initial3_3,不可行,0,可行,20,種群總fit,28057,'1'個數,372,'0'個數,1428
run_2,prob_28,algorithm_initial3_3,不可行,0,可行,20,種群總fit,27489,'1'個數,361,'0'個數,1439
run_2,prob_29,algorithm_initial3_3,不可行,0,可行,20,種群總fit,27967,'1'個數,337,'0'個數,1463
run_2,prob_30,algorithm_initial3_3,不可行,0,可行,20,種群總fit,38725,'1'個數,508,'0'個數,1292
run_3,prob_01,algorithm_initial3_3,不可行,0,可行,20,種群總fit,17841,'1'個數,175,'0'個數,425
run_3,prob_02,algorithm_initial3_3,不可行,0,可行,20,種群總fit,16404,'1'個數,176,'0'個數,424
run_3,prob_03,algorithm_initial3_3,不可行,0,可行,20,種群總fit,11769,'1'個數,121,'0'個數,479
run_3,prob_04,algorithm_initial3_3,不可行,0,可行,20,種群總fit,8595,'1'個數,98,'0'個數,502
run_3,prob_05,algorithm_initial3_3,不可行,0,可行,20,種群總fit,8759,'1'個數,92,'0'個數,508
run_3,prob_06,algorithm_initial3_3,不可行,0,可行,20,種群總fit,20903,'1'個數,260,'0'個數,540
run_3,prob_07,algorithm_initial3_3,不可行,0,可行,20,種群總fit,20338,'1'個數,227,'0'個數,573
run_3,prob_08,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21524,'1'個數,249,'0'個數,551
run_3,prob_09,algorithm_initial3_3,不可行,0,可行,20,種群總fit,11256,'1'個數,140,'0'個數,660
run_3,prob_10,algorithm_initial3_3,不可行,0,可行,20,種群總fit,14655,'1'個數,177,'0'個數,823
run_3,prob_11,algorithm_initial3_3,不可行,0,可行,20,種群總fit,10265,'1'個數,127,'0'個數,873
run_3,prob_12,algorithm_initial3_3,不可行,0,可行,20,種群總fit,15681,'1'個數,182,'0'個數,818
run_3,prob_13,algorithm_initial3_3,不可行,0,可行,20,種群總fit,14081,'1'個數,158,'0'個數,842
run_3,prob_14,algorithm_initial3_3,不可行,0,可行,20,種群總fit,16986,'1'個數,211,'0'個數,989
run_3,prob_15,algorithm_initial3_3,不可行,0,可行,20,種群總fit,13882,'1'個數,179,'0'個數,1021
run_3,prob_16,algorithm_initial3_3,不可行,0,可行,20,種群總fit,23740,'1'個數,259,'0'個數,941
run_3,prob_17,algorithm_initial3_3,不可行,0,可行,20,種群總fit,39738,'1'個數,487,'0'個數,713
run_3,prob_18,algorithm_initial3_3,不可行,0,可行,20,種群總fit,44609,'1'個數,462,'0'個數,938
run_3,prob_19,algorithm_initial3_3,不可行,0,可行,20,種群總fit,23426,'1'個數,260,'0'個數,1140
run_3,prob_20,algorithm_initial3_3,不可行,0,可行,20,種群總fit,28769,'1'個數,337,'0'個數,1063
run_3,prob_21,algorithm_initial3_3,不可行,0,可行,20,種群總fit,23105,'1'個數,275,'0'個數,1125
run_3,prob_22,algorithm_initial3_3,不可行,0,可行,20,種群總fit,27771,'1'個數,343,'0'個數,1257
run_3,prob_23,algorithm_initial3_3,不可行,0,可行,20,種群總fit,24458,'1'個數,296,'0'個數,1304
run_3,prob_24,algorithm_initial3_3,不可行,0,可行,20,種群總fit,42455,'1'個數,531,'0'個數,1069
run_3,prob_25,algorithm_initial3_3,不可行,0,可行,20,種群總fit,30157,'1'個數,381,'0'個數,1219
run_3,prob_26,algorithm_initial3_3,不可行,0,可行,20,種群總fit,28237,'1'個數,340,'0'個數,1460
run_3,prob_27,algorithm_initial3_3,不可行,0,可行,20,種群總fit,31129,'1'個數,373,'0'個數,1427
run_3,prob_28,algorithm_initial3_3,不可行,0,可行,20,種群總fit,25987,'1'個數,326,'0'個數,1474
run_3,prob_29,algorithm_initial3_3,不可行,0,可行,20,種群總fit,27939,'1'個數,338,'0'個數,1462
run_3,prob_30,algorithm_initial3_3,不可行,0,可行,20,種群總fit,42331,'1'個數,507,'0'個數,1293
run_4,prob_01,algorithm_initial3_3,不可行,0,可行,20,種群總fit,18273,'1'個數,178,'0'個數,422
run_4,prob_02,algorithm_initial3_3,不可行,0,可行,20,種群總fit,18646,'1'個數,182,'0'個數,418
run_4,prob_03,algorithm_initial3_3,不可行,0,可行,20,種群總fit,11843,'1'個數,132,'0'個數,468
run_4,prob_04,algorithm_initial3_3,不可行,0,可行,20,種群總fit,9270,'1'個數,100,'0'個數,500
run_4,prob_05,algorithm_initial3_3,不可行,0,可行,20,種群總fit,6978,'1'個數,88,'0'個數,512
run_4,prob_06,algorithm_initial3_3,不可行,0,可行,20,種群總fit,19582,'1'個數,253,'0'個數,547
run_4,prob_07,algorithm_initial3_3,不可行,0,可行,20,種群總fit,20809,'1'個數,248,'0'個數,552
run_4,prob_08,algorithm_initial3_3,不可行,0,可行,20,種群總fit,22950,'1'個數,250,'0'個數,550
run_4,prob_09,algorithm_initial3_3,不可行,0,可行,20,種群總fit,12619,'1'個數,152,'0'個數,648
run_4,prob_10,algorithm_initial3_3,不可行,0,可行,20,種群總fit,16868,'1'個數,178,'0'個數,822
run_4,prob_11,algorithm_initial3_3,不可行,0,可行,20,種群總fit,9888,'1'個數,120,'0'個數,880
run_4,prob_12,algorithm_initial3_3,不可行,0,可行,20,種群總fit,12908,'1'個數,160,'0'個數,840
run_4,prob_13,algorithm_initial3_3,不可行,0,可行,20,種群總fit,12400,'1'個數,152,'0'個數,848
run_4,prob_14,algorithm_initial3_3,不可行,0,可行,20,種群總fit,16661,'1'個數,212,'0'個數,988
run_4,prob_15,algorithm_initial3_3,不可行,0,可行,20,種群總fit,14614,'1'個數,186,'0'個數,1014
run_4,prob_16,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21873,'1'個數,263,'0'個數,937
run_4,prob_17,algorithm_initial3_3,不可行,0,可行,20,種群總fit,44707,'1'個數,495,'0'個數,705
run_4,prob_18,algorithm_initial3_3,不可行,0,可行,20,種群總fit,36923,'1'個數,441,'0'個數,959
run_4,prob_19,algorithm_initial3_3,不可行,0,可行,20,種群總fit,22837,'1'個數,243,'0'個數,1157
run_4,prob_20,algorithm_initial3_3,不可行,0,可行,20,種群總fit,31092,'1'個數,329,'0'個數,1071
run_4,prob_21,algorithm_initial3_3,不可行,0,可行,20,種群總fit,23801,'1'個數,276,'0'個數,1124
run_4,prob_22,algorithm_initial3_3,不可行,0,可行,20,種群總fit,30727,'1'個數,347,'0'個數,1253
run_4,prob_23,algorithm_initial3_3,不可行,0,可行,20,種群總fit,24362,'1'個數,289,'0'個數,1311
run_4,prob_24,algorithm_initial3_3,不可行,0,可行,20,種群總fit,47971,'1'個數,547,'0'個數,1053
run_4,prob_25,algorithm_initial3_3,不可行,0,可行,20,種群總fit,28552,'1'個數,382,'0'個數,1218
run_4,prob_26,algorithm_initial3_3,不可行,0,可行,20,種群總fit,27160,'1'個數,357,'0'個數,1443
run_4,prob_27,algorithm_initial3_3,不可行,0,可行,20,種群總fit,30557,'1'個數,386,'0'個數,1414
run_4,prob_28,algorithm_initial3_3,不可行,0,可行,20,種群總fit,28656,'1'個數,341,'0'個數,1459
run_4,prob_29,algorithm_initial3_3,不可行,0,可行,20,種群總fit,27620,'1'個數,325,'0'個數,1475
run_4,prob_30,algorithm_initial3_3,不可行,0,可行,20,種群總fit,41721,'1'個數,507,'0'個數,1293
run_5,prob_01,algorithm_initial3_3,不可行,0,可行,20,種群總fit,17485,'1'個數,184,'0'個數,416
run_5,prob_02,algorithm_initial3_3,不可行,0,可行,20,種群總fit,18780,'1'個數,192,'0'個數,408
run_5,prob_03,algorithm_initial3_3,不可行,0,可行,20,種群總fit,11245,'1'個數,109,'0'個數,491
run_5,prob_04,algorithm_initial3_3,不可行,0,可行,20,種群總fit,10054,'1'個數,100,'0'個數,500
run_5,prob_05,algorithm_initial3_3,不可行,0,可行,20,種群總fit,6521,'1'個數,81,'0'個數,519
run_5,prob_06,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21018,'1'個數,241,'0'個數,559
run_5,prob_07,algorithm_initial3_3,不可行,0,可行,20,種群總fit,20104,'1'個數,239,'0'個數,561
run_5,prob_08,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21113,'1'個數,256,'0'個數,544
run_5,prob_09,algorithm_initial3_3,不可行,0,可行,20,種群總fit,13965,'1'個數,164,'0'個數,636
run_5,prob_10,algorithm_initial3_3,不可行,0,可行,20,種群總fit,14745,'1'個數,179,'0'個數,821
run_5,prob_11,algorithm_initial3_3,不可行,0,可行,20,種群總fit,9940,'1'個數,118,'0'個數,882
run_5,prob_12,algorithm_initial3_3,不可行,0,可行,20,種群總fit,12025,'1'個數,168,'0'個數,832
run_5,prob_13,algorithm_initial3_3,不可行,0,可行,20,種群總fit,12974,'1'個數,149,'0'個數,851
run_5,prob_14,algorithm_initial3_3,不可行,0,可行,20,種群總fit,15942,'1'個數,215,'0'個數,985
run_5,prob_15,algorithm_initial3_3,不可行,0,可行,20,種群總fit,15913,'1'個數,194,'0'個數,1006
run_5,prob_16,algorithm_initial3_3,不可行,0,可行,20,種群總fit,20404,'1'個數,261,'0'個數,939
run_5,prob_17,algorithm_initial3_3,不可行,0,可行,20,種群總fit,41716,'1'個數,482,'0'個數,718
run_5,prob_18,algorithm_initial3_3,不可行,0,可行,20,種群總fit,42529,'1'個數,468,'0'個數,932
run_5,prob_19,algorithm_initial3_3,不可行,0,可行,20,種群總fit,23595,'1'個數,251,'0'個數,1149
run_5,prob_20,algorithm_initial3_3,不可行,0,可行,20,種群總fit,29577,'1'個數,342,'0'個數,1058
run_5,prob_21,algorithm_initial3_3,不可行,0,可行,20,種群總fit,25495,'1'個數,268,'0'個數,1132
run_5,prob_22,algorithm_initial3_3,不可行,0,可行,20,種群總fit,28865,'1'個數,351,'0'個數,1249
run_5,prob_23,algorithm_initial3_3,不可行,0,可行,20,種群總fit,23792,'1'個數,282,'0'個數,1318
run_5,prob_24,algorithm_initial3_3,不可行,0,可行,20,種群總fit,46516,'1'個數,544,'0'個數,1056
run_5,prob_25,algorithm_initial3_3,不可行,0,可行,20,種群總fit,31354,'1'個數,370,'0'個數,1230
run_5,prob_26,algorithm_initial3_3,不可行,0,可行,20,種群總fit,27057,'1'個數,332,'0'個數,1468
run_5,prob_27,algorithm_initial3_3,不可行,0,可行,20,種群總fit,30914,'1'個數,389,'0'個數,1411
run_5,prob_28,algorithm_initial3_3,不可行,0,可行,20,種群總fit,28843,'1'個數,341,'0'個數,1459
run_5,prob_29,algorithm_initial3_3,不可行,0,可行,20,種群總fit,27435,'1'個數,331,'0'個數,1469
run_5,prob_30,algorithm_initial3_3,不可行,0,可行,20,種群總fit,42547,'1'個數,491,'0'個數,1309
run_6,prob_01,algorithm_initial3_3,不可行,0,可行,20,種群總fit,19218,'1'個數,182,'0'個數,418
run_6,prob_02,algorithm_initial3_3,不可行,0,可行,20,種群總fit,17409,'1'個數,181,'0'個數,419
run_6,prob_03,algorithm_initial3_3,不可行,0,可行,20,種群總fit,11226,'1'個數,117,'0'個數,483
run_6,prob_04,algorithm_initial3_3,不可行,0,可行,20,種群總fit,10730,'1'個數,99,'0'個數,501
run_6,prob_05,algorithm_initial3_3,不可行,0,可行,20,種群總fit,6299,'1'個數,79,'0'個數,521
run_6,prob_06,algorithm_initial3_3,不可行,0,可行,20,種群總fit,22277,'1'個數,259,'0'個數,541
run_6,prob_07,algorithm_initial3_3,不可行,0,可行,20,種群總fit,20380,'1'個數,240,'0'個數,560
run_6,prob_08,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21253,'1'個數,239,'0'個數,561
run_6,prob_09,algorithm_initial3_3,不可行,0,可行,20,種群總fit,12363,'1'個數,144,'0'個數,656
run_6,prob_10,algorithm_initial3_3,不可行,0,可行,20,種群總fit,15723,'1'個數,171,'0'個數,829
run_6,prob_11,algorithm_initial3_3,不可行,0,可行,20,種群總fit,10346,'1'個數,117,'0'個數,883
run_6,prob_12,algorithm_initial3_3,不可行,0,可行,20,種群總fit,13963,'1'個數,166,'0'個數,834
run_6,prob_13,algorithm_initial3_3,不可行,0,可行,20,種群總fit,12532,'1'個數,149,'0'個數,851
run_6,prob_14,algorithm_initial3_3,不可行,0,可行,20,種群總fit,16269,'1'個數,206,'0'個數,994
run_6,prob_15,algorithm_initial3_3,不可行,0,可行,20,種群總fit,15273,'1'個數,187,'0'個數,1013
run_6,prob_16,algorithm_initial3_3,不可行,0,可行,20,種群總fit,20535,'1'個數,265,'0'個數,935
run_6,prob_17,algorithm_initial3_3,不可行,0,可行,20,種群總fit,42584,'1'個數,491,'0'個數,709
run_6,prob_18,algorithm_initial3_3,不可行,0,可行,20,種群總fit,41415,'1'個數,477,'0'個數,923
run_6,prob_19,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21702,'1'個數,253,'0'個數,1147
run_6,prob_20,algorithm_initial3_3,不可行,0,可行,20,種群總fit,25504,'1'個數,316,'0'個數,1084
run_6,prob_21,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21586,'1'個數,263,'0'個數,1137
run_6,prob_22,algorithm_initial3_3,不可行,0,可行,20,種群總fit,27148,'1'個數,340,'0'個數,1260
run_6,prob_23,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21818,'1'個數,269,'0'個數,1331
run_6,prob_24,algorithm_initial3_3,不可行,0,可行,20,種群總fit,45676,'1'個數,539,'0'個數,1061
run_6,prob_25,algorithm_initial3_3,不可行,0,可行,20,種群總fit,30141,'1'個數,376,'0'個數,1224
run_6,prob_26,algorithm_initial3_3,不可行,0,可行,20,種群總fit,25048,'1'個數,331,'0'個數,1469
run_6,prob_27,algorithm_initial3_3,不可行,0,可行,20,種群總fit,30400,'1'個數,358,'0'個數,1442
run_6,prob_28,algorithm_initial3_3,不可行,0,可行,20,種群總fit,28118,'1'個數,321,'0'個數,1479
run_6,prob_29,algorithm_initial3_3,不可行,0,可行,20,種群總fit,25021,'1'個數,324,'0'個數,1476
run_6,prob_30,algorithm_initial3_3,不可行,0,可行,20,種群總fit,42590,'1'個數,520,'0'個數,1280
run_7,prob_01,algorithm_initial3_3,不可行,0,可行,20,種群總fit,18187,'1'個數,182,'0'個數,418
run_7,prob_02,algorithm_initial3_3,不可行,0,可行,20,種群總fit,19044,'1'個數,184,'0'個數,416
run_7,prob_03,algorithm_initial3_3,不可行,0,可行,20,種群總fit,11863,'1'個數,115,'0'個數,485
run_7,prob_04,algorithm_initial3_3,不可行,0,可行,20,種群總fit,8452,'1'個數,97,'0'個數,503
run_7,prob_05,algorithm_initial3_3,不可行,0,可行,20,種群總fit,8575,'1'個數,88,'0'個數,512
run_7,prob_06,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21135,'1'個數,252,'0'個數,548
run_7,prob_07,algorithm_initial3_3,不可行,0,可行,20,種群總fit,19142,'1'個數,230,'0'個數,570
run_7,prob_08,algorithm_initial3_3,不可行,0,可行,20,種群總fit,20292,'1'個數,236,'0'個數,564
run_7,prob_09,algorithm_initial3_3,不可行,0,可行,20,種群總fit,11786,'1'個數,135,'0'個數,665
run_7,prob_10,algorithm_initial3_3,不可行,0,可行,20,種群總fit,13443,'1'個數,172,'0'個數,828
run_7,prob_11,algorithm_initial3_3,不可行,0,可行,20,種群總fit,8944,'1'個數,117,'0'個數,883
run_7,prob_12,algorithm_initial3_3,不可行,0,可行,20,種群總fit,14850,'1'個數,158,'0'個數,842
run_7,prob_13,algorithm_initial3_3,不可行,0,可行,20,種群總fit,12478,'1'個數,161,'0'個數,839
run_7,prob_14,algorithm_initial3_3,不可行,0,可行,20,種群總fit,16485,'1'個數,219,'0'個數,981
run_7,prob_15,algorithm_initial3_3,不可行,0,可行,20,種群總fit,16368,'1'個數,186,'0'個數,1014
run_7,prob_16,algorithm_initial3_3,不可行,0,可行,20,種群總fit,18502,'1'個數,242,'0'個數,958
run_7,prob_17,algorithm_initial3_3,不可行,0,可行,20,種群總fit,40380,'1'個數,476,'0'個數,724
run_7,prob_18,algorithm_initial3_3,不可行,0,可行,20,種群總fit,40878,'1'個數,474,'0'個數,926
run_7,prob_19,algorithm_initial3_3,不可行,0,可行,20,種群總fit,23341,'1'個數,250,'0'個數,1150
run_7,prob_20,algorithm_initial3_3,不可行,0,可行,20,種群總fit,28659,'1'個數,324,'0'個數,1076
run_7,prob_21,algorithm_initial3_3,不可行,0,可行,20,種群總fit,23697,'1'個數,273,'0'個數,1127
run_7,prob_22,algorithm_initial3_3,不可行,0,可行,20,種群總fit,29490,'1'個數,342,'0'個數,1258
run_7,prob_23,algorithm_initial3_3,不可行,0,可行,20,種群總fit,22197,'1'個數,280,'0'個數,1320
run_7,prob_24,algorithm_initial3_3,不可行,0,可行,20,種群總fit,48499,'1'個數,544,'0'個數,1056
run_7,prob_25,algorithm_initial3_3,不可行,0,可行,20,種群總fit,28037,'1'個數,376,'0'個數,1224
run_7,prob_26,algorithm_initial3_3,不可行,0,可行,20,種群總fit,28010,'1'個數,345,'0'個數,1455
run_7,prob_27,algorithm_initial3_3,不可行,0,可行,20,種群總fit,31087,'1'個數,384,'0'個數,1416
run_7,prob_28,algorithm_initial3_3,不可行,0,可行,20,種群總fit,27696,'1'個數,350,'0'個數,1450
run_7,prob_29,algorithm_initial3_3,不可行,0,可行,20,種群總fit,26057,'1'個數,326,'0'個數,1474
run_7,prob_30,algorithm_initial3_3,不可行,0,可行,20,種群總fit,41468,'1'個數,508,'0'個數,1292
run_8,prob_01,algorithm_initial3_3,不可行,0,可行,20,種群總fit,17420,'1'個數,184,'0'個數,416
run_8,prob_02,algorithm_initial3_3,不可行,0,可行,20,種群總fit,18424,'1'個數,181,'0'個數,419
run_8,prob_03,algorithm_initial3_3,不可行,0,可行,20,種群總fit,10969,'1'個數,119,'0'個數,481
run_8,prob_04,algorithm_initial3_3,不可行,0,可行,20,種群總fit,8480,'1'個數,97,'0'個數,503
run_8,prob_05,algorithm_initial3_3,不可行,0,可行,20,種群總fit,7652,'1'個數,83,'0'個數,517
run_8,prob_06,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21790,'1'個數,253,'0'個數,547
run_8,prob_07,algorithm_initial3_3,不可行,0,可行,20,種群總fit,18987,'1'個數,232,'0'個數,568
run_8,prob_08,algorithm_initial3_3,不可行,0,可行,20,種群總fit,21355,'1'個數,264,'0'個數,536
run_8,prob_09,algorithm_initial3_3,不可行,0,可行,20,種群總fit,14497,'1'個數,147,'0'個數,653

In [ ]:
fessible_log[f"log_run_0_prob_01_algorithm_initial3"]

["log_run_0\t prob_01\t algorithm_initial3 \t 不可行\t0 \t 可行 \t20 \t 種群總fit \t 17224\t'1'個數 \t 187\t '0'個數 \t413"]

In [ ]:
# 第 i 次執行中 0 或 1 的統計數量

fessible_log = {} # 紀錄空間
for i in range(run_time):
    for j in main.problem1:
        for k in range(len(main.r2)):
            subset = initial_log[f"initial2_log_run_{i}_prob_{j}_r2_{k}"].iloc[:, 1:-1] # 初始解的決策變數
            counts_1 = (subset.values == 1).sum() # 計算是 1 的數量
            counts_0 = (subset.values == 0).sum() # 計算是 0 的數量



            fitness = initial_log[f"initial1_log_run_{i}_prob_{j}_r2_{k}"].iloc[:,-1].values
            tatal_fit = np.sum(fitness)
            # print(fitness)
            fessible = 0 # 可行
            infessible = 0 # 不可行
            for l in range(log_pop_size):
                if fitness[l] < 0 :
                    infessible += 1
                else:
                    fessible += 1
            fessible_log[f"initial1_log_run_{i}_prob_{j}_r2_{k}"] =  [""]
            print(f": 不可行:{infessible}\t可行:{fessible}\t種群總fit:{int(tatal_fit)}\t'1'個數:{counts_1}\t'0'個數:{counts_0}\n")

run_0/problem_01/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-11753	'1'個數:496	'0'個數:104

run_0/problem_01/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-8965	'1'個數:413	'0'個數:187

run_0/problem_01/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-5621	'1'個數:331	'0'個數:269

run_0/problem_01/infessible/r2_0.5 : 不可行:16	可行:4	種群總fit:3159	'1'個數:285	'0'個數:315

run_0/problem_01/infessible/r2_0.6 : 不可行:13	可行:7	種群總fit:9665	'1'個數:239	'0'個數:361

run_0/problem_01/infessible/r2_0.7 : 不可行:9	可行:11	種群總fit:14571	'1'個數:194	'0'個數:406

run_0/problem_01/infessible/r2_0.8 : 不可行:2	可行:18	種群總fit:19181	'1'個數:115	'0'個數:485

run_0/problem_01/infessible/r2_None : 不可行:11	可行:9	種群總fit:7650	'1'個數:292	'0'個數:308

run_0/problem_02/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-10071	'1'個數:475	'0'個數:125

run_0/problem_02/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-7735	'1'個數:415	'0'個數:185

run_0/problem_02/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-6247	'1'個數:372	'0'個數:228

run_0/problem_02/infessible/r2_0.5 : 不可行:18	可行:2	種群總fit:1182	'1'個數:299	'0'個數:301

run_0/problem_02/infessible/r2_0.6 : 不可行:15	可行:5	種群總fit:6088	'1'個數:250	'0'個數:350

run_0/problem_02/infessible/r2_0.7 : 不可行:4	可行:16	種群總fit:26138	'1'個數:165	'0'個數:435

run_0/problem_02/infessible/r2_0.8 : 不可行:4	可行:16	種群總fit:16819	'1'個數:127	'0'個數:473

run_0/problem_02/infessible/r2_None : 不可行:10	可行:10	種群總fit:8715	'1'個數:212	'0'個數:388

run_0/problem_03/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-14835	'1'個數:467	'0'個數:133

run_0/problem_03/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-12210	'1'個數:420	'0'個數:180

run_0/problem_03/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-9526	'1'個數:357	'0'個數:243

run_0/problem_03/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-7252	'1'個數:303	'0'個數:297

run_0/problem_03/infessible/r2_0.6 : 不可行:19	可行:1	種群總fit:-1828	'1'個數:225	'0'個數:375

run_0/problem_03/infessible/r2_0.7 : 不可行:16	可行:4	種群總fit:4841	'1'個數:173	'0'個數:427

run_0/problem_03/infessible/r2_0.8 : 不可行:10	可行:10	種群總fit:8969	'1'個數:129	'0'個數:471

run_0/problem_03/infessible/r2_None : 不可行:15	可行:5	種群總fit:-2719	'1'個數:263	'0'個數:337

run_0/problem_04/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-15536	'1'個數:492	'0'個數:108

run_0/problem_04/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-11984	'1'個數:423	'0'個數:177

run_0/problem_04/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-9704	'1'個數:358	'0'個數:242

run_0/problem_04/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-7400	'1'個數:303	'0'個數:297

run_0/problem_04/infessible/r2_0.6 : 不可行:20	可行:0	種群總fit:-4600	'1'個數:237	'0'個數:363

run_0/problem_04/infessible/r2_0.7 : 不可行:12	可行:8	種群總fit:8010	'1'個數:168	'0'個數:432

run_0/problem_04/infessible/r2_0.8 : 不可行:9	可行:11	種群總fit:14361	'1'個數:124	'0'個數:476

run_0/problem_04/infessible/r2_None : 不可行:15	可行:5	種群總fit:-5454	'1'個數:280	'0'個數:320

run_0/problem_05/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-14850	'1'個數:465	'0'個數:135

run_0/problem_05/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-13695	'1'個數:428	'0'個數:172

run_0/problem_05/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-10456	'1'個數:359	'0'個數:241

run_0/problem_05/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-8263	'1'個數:306	'0'個數:294

run_0/problem_05/infessible/r2_0.6 : 不可行:20	可行:0	種群總fit:-5284	'1'個數:244	'0'個數:356

run_0/problem_05/infessible/r2_0.7 : 不可行:18	可行:2	種群總fit:-1938	'1'個數:186	'0'個數:414

run_0/problem_05/infessible/r2_0.8 : 不可行:14	可行:6	種群總fit:5264	'1'個數:114	'0'個數:486

run_0/problem_05/infessible/r2_None : 不可行:15	可行:5	種群總fit:-4917	'1'個數:273	'0'個數:327

run_0/problem_06/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-12123	'1'個數:629	'0'個數:171

run_0/problem_06/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-9915	'1'個數:550	'0'個數:250

run_0/problem_06/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-7550	'1'個數:499	'0'個數:301

run_0/problem_06/infessible/r2_0.5 : 不可行:19	可行:1	種群總fit:-1743	'1'個數:396	'0'個數:404

run_0/problem_06/infessible/r2_0.6 : 不可行:14	可行:6	種群總fit:10755	'1'個數:311	'0'個數:489

run_0/problem_06/infessible/r2_0.7 : 不可行:7	可行:13	種群總fit:21411	'1'個數:248	'0'個數:552

run_0/problem_06/infessible/r2_0.8 : 不可行:0	可行:20	種群總fit:26680	'1'個數:160	'0'個數:640

run_0/problem_06/infessible/r2_None : 不可行:10	可行:10	種群總fit:4506	'1'個數:364	'0'個數:436

run_0/problem_07/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-13803	'1'個數:655	'0'個數:145

run_0/problem_07/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-10794	'1'個數:558	'0'個數:242

run_0/problem_07/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-8468	'1'個數:496	'0'個數:304

run_0/problem_07/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-4634	'1'個數:400	'0'個數:400

run_0/problem_07/infessible/r2_0.6 : 不可行:16	可行:4	種群總fit:5945	'1'個數:309	'0'個數:491

run_0/problem_07/infessible/r2_0.7 : 不可行:11	可行:9	種群總fit:16920	'1'個數:258	'0'個數:542

run_0/problem_07/infessible/r2_0.8 : 不可行:0	可行:20	種群總fit:28936	'1'個數:167	'0'個數:633

run_0/problem_07/infessible/r2_None : 不可行:14	可行:6	種群總fit:-2930	'1'個數:422	'0'個數:378

run_0/problem_08/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-12773	'1'個數:627	'0'個數:173

run_0/problem_08/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-9935	'1'個數:569	'0'個數:231

run_0/problem_08/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-7062	'1'個數:468	'0'個數:332

run_0/problem_08/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-4154	'1'個數:390	'0'個數:410

run_0/problem_08/infessible/r2_0.6 : 不可行:15	可行:5	種群總fit:7238	'1'個數:326	'0'個數:474

run_0/problem_08/infessible/r2_0.7 : 不可行:5	可行:15	種群總fit:22713	'1'個數:235	'0'個數:565

run_0/problem_08/infessible/r2_0.8 : 不可行:1	可行:19	種群總fit:28849	'1'個數:175	'0'個數:625

run_0/problem_08/infessible/r2_None : 不可行:12	可行:8	種群總fit:2525	'1'個數:421	'0'個數:379

run_0/problem_09/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-17904	'1'個數:626	'0'個數:174

run_0/problem_09/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-16767	'1'個數:587	'0'個數:213

run_0/problem_09/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-12520	'1'個數:480	'0'個數:320

run_0/problem_09/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-8398	'1'個數:395	'0'個數:405

run_0/problem_09/infessible/r2_0.6 : 不可行:19	可行:1	種群總fit:-4177	'1'個數:326	'0'個數:474

run_0/problem_09/infessible/r2_0.7 : 不可行:17	可行:3	種群總fit:1143	'1'個數:245	'0'個數:555

run_0/problem_09/infessible/r2_0.8 : 不可行:6	可行:14	種群總fit:16610	'1'個數:166	'0'個數:634

run_0/problem_09/infessible/r2_None : 不可行:14	可行:6	種群總fit:-4522	'1'個數:379	'0'個數:421

run_0/problem_10/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-24092	'1'個數:796	'0'個數:204

run_0/problem_10/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-21015	'1'個數:696	'0'個數:304

run_0/problem_10/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-17915	'1'個數:613	'0'個數:387

run_0/problem_10/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-12455	'1'個數:501	'0'個數:499

run_0/problem_10/infessible/r2_0.6 : 不可行:20	可行:0	種群總fit:-8311	'1'個數:403	'0'個數:597

run_0/problem_10/infessible/r2_0.7 : 不可行:19	可行:1	種群總fit:-970	'1'個數:302	'0'個數:698

run_0/problem_10/infessible/r2_0.8 : 不可行:10	可行:10	種群總fit:14690	'1'個數:220	'0'個數:780

run_0/problem_10/infessible/r2_None : 不可行:15	可行:5	種群總fit:-5437	'1'個數:479	'0'個數:521

run_0/problem_11/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-28024	'1'個數:795	'0'個數:205

run_0/problem_11/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-23707	'1'個數:698	'0'個數:302

run_0/problem_11/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-19690	'1'個數:602	'0'個數:398

run_0/problem_11/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-14090	'1'個數:469	'0'個數:531

run_0/problem_11/infessible/r2_0.6 : 不可行:20	可行:0	種群總fit:-9089	'1'個數:366	'0'個數:634

run_0/problem_11/infessible/r2_0.7 : 不可行:20	可行:0	種群總fit:-8311	'1'個數:323	'0'個數:677

run_0/problem_11/infessible/r2_0.8 : 不可行:14	可行:6	種群總fit:5479	'1'個數:215	'0'個數:785

run_0/problem_11/infessible/r2_None : 不可行:16	可行:4	種群總fit:-14245	'1'個數:482	'0'個數:518

run_0/problem_12/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-25298	'1'個數:812	'0'個數:188

run_0/problem_12/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-20380	'1'個數:704	'0'個數:296

run_0/problem_12/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-17085	'1'個數:593	'0'個數:407

run_0/problem_12/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-11872	'1'個數:477	'0'個數:523

run_0/problem_12/infessible/r2_0.6 : 不可行:20	可行:0	種群總fit:-7224	'1'個數:385	'0'個數:615

run_0/problem_12/infessible/r2_0.7 : 不可行:15	可行:5	種群總fit:6562	'1'個數:280	'0'個數:720

run_0/problem_12/infessible/r2_0.8 : 不可行:8	可行:12	種群總fit:15101	'1'個數:192	'0'個數:808

run_0/problem_12/infessible/r2_None : 不可行:15	可行:5	種群總fit:-3876	'1'個數:441	'0'個數:559

run_0/problem_13/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-26163	'1'個數:814	'0'個數:186

run_0/problem_13/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-22363	'1'個數:704	'0'個數:296

run_0/problem_13/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-18013	'1'個數:605	'0'個數:395

run_0/problem_13/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-14337	'1'個數:520	'0'個數:480

run_0/problem_13/infessible/r2_0.6 : 不可行:20	可行:0	種群總fit:-8355	'1'個數:412	'0'個數:588

run_0/problem_13/infessible/r2_0.7 : 不可行:19	可行:1	種群總fit:-2887	'1'個數:294	'0'個數:706

run_0/problem_13/infessible/r2_0.8 : 不可行:13	可行:7	種群總fit:7597	'1'個數:197	'0'個數:803

run_0/problem_13/infessible/r2_None : 不可行:16	可行:4	種群總fit:-10887	'1'個數:479	'0'個數:521

run_0/problem_14/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-29440	'1'個數:965	'0'個數:235

run_0/problem_14/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-24936	'1'個數:864	'0'個數:336

run_0/problem_14/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-18981	'1'個數:710	'0'個數:490

run_0/problem_14/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-13274	'1'個數:591	'0'個數:609

run_0/problem_14/infessible/r2_0.6 : 不可行:20	可行:0	種群總fit:-9340	'1'個數:489	'0'個數:711

run_0/problem_14/infessible/r2_0.7 : 不可行:16	可行:4	種群總fit:2315	'1'個數:344	'0'個數:856

run_0/problem_14/infessible/r2_0.8 : 不可行:12	可行:8	種群總fit:9668	'1'個數:259	'0'個數:941

run_0/problem_14/infessible/r2_None : 不可行:16	可行:4	種群總fit:-11855	'1'個數:579	'0'個數:621

run_0/problem_15/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-27698	'1'個數:980	'0'個數:220

run_0/problem_15/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-21994	'1'個數:825	'0'個數:375

run_0/problem_15/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-18499	'1'個數:729	'0'個數:471

run_0/problem_15/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-13138	'1'個數:573	'0'個數:627

run_0/problem_15/infessible/r2_0.6 : 不可行:20	可行:0	種群總fit:-11376	'1'個數:524	'0'個數:676

run_0/problem_15/infessible/r2_0.7 : 不可行:18	可行:2	種群總fit:-51	'1'個數:367	'0'個數:833

run_0/problem_15/infessible/r2_0.8 : 不可行:13	可行:7	種群總fit:8081	'1'個數:222	'0'個數:978

run_0/problem_15/infessible/r2_None : 不可行:14	可行:6	種群總fit:-7332	'1'個數:520	'0'個數:680

run_0/problem_16/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-29336	'1'個數:975	'0'個數:225

run_0/problem_16/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-23985	'1'個數:865	'0'個數:335

run_0/problem_16/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-18726	'1'個數:735	'0'個數:465

run_0/problem_16/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-10788	'1'個數:563	'0'個數:637

run_0/problem_16/infessible/r2_0.6 : 不可行:18	可行:2	種群總fit:-3194	'1'個數:470	'0'個數:730

run_0/problem_16/infessible/r2_0.7 : 不可行:16	可行:4	種群總fit:5826	'1'個數:361	'0'個數:839

run_0/problem_16/infessible/r2_0.8 : 不可行:4	可行:16	種群總fit:28406	'1'個數:243	'0'個數:957

run_0/problem_16/infessible/r2_None : 不可行:17	可行:3	種群總fit:-14345	'1'個數:697	'0'個數:503

run_0/problem_17/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-17525	'1'個數:956	'0'個數:244

run_0/problem_17/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-12395	'1'個數:857	'0'個數:343

run_0/problem_17/infessible/r2_0.4 : 不可行:19	可行:1	種群總fit:-3091	'1'個數:721	'0'個數:479

run_0/problem_17/infessible/r2_0.5 : 不可行:15	可行:5	種群總fit:20768	'1'個數:605	'0'個數:595

run_0/problem_17/infessible/r2_0.6 : 不可行:4	可行:16	種群總fit:57226	'1'個數:486	'0'個數:714

run_0/problem_17/infessible/r2_0.7 : 不可行:0	可行:20	種群總fit:60568	'1'個數:365	'0'個數:835

run_0/problem_17/infessible/r2_0.8 : 不可行:0	可行:20	種群總fit:36387	'1'個數:230	'0'個數:970

run_0/problem_17/infessible/r2_None : 不可行:9	可行:11	種群總fit:21064	'1'個數:608	'0'個數:592

run_0/problem_18/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-22570	'1'個數:1131	'0'個數:269

run_0/problem_18/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-17041	'1'個數:963	'0'個數:437

run_0/problem_18/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-14392	'1'個數:885	'0'個數:515

run_0/problem_18/infessible/r2_0.5 : 不可行:19	可行:1	種群總fit:-736	'1'個數:663	'0'個數:737

run_0/problem_18/infessible/r2_0.6 : 不可行:13	可行:7	種群總fit:21196	'1'個數:584	'0'個數:816

run_0/problem_18/infessible/r2_0.7 : 不可行:4	可行:16	種群總fit:60256	'1'個數:433	'0'個數:967

run_0/problem_18/infessible/r2_0.8 : 不可行:0	可行:20	種群總fit:43860	'1'個數:296	'0'個數:1104

run_0/problem_18/infessible/r2_None : 不可行:12	可行:8	種群總fit:6376	'1'個數:665	'0'個數:735

run_0/problem_19/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-37431	'1'個數:1119	'0'個數:281

run_0/problem_19/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-31236	'1'個數:998	'0'個數:402

run_0/problem_19/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-24331	'1'個數:835	'0'個數:565

run_0/problem_19/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-17275	'1'個數:680	'0'個數:720

run_0/problem_19/infessible/r2_0.6 : 不可行:20	可行:0	種群總fit:-13489	'1'個數:586	'0'個數:814

run_0/problem_19/infessible/r2_0.7 : 不可行:18	可行:2	種群總fit:-776	'1'個數:425	'0'個數:975

run_0/problem_19/infessible/r2_0.8 : 不可行:10	可行:10	種群總fit:18183	'1'個數:276	'0'個數:1124

run_0/problem_19/infessible/r2_None : 不可行:15	可行:5	種群總fit:-9500	'1'個數:670	'0'個數:730

run_0/problem_20/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-27152	'1'個數:1115	'0'個數:285

run_0/problem_20/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-22842	'1'個數:995	'0'個數:405

run_0/problem_20/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-16150	'1'個數:835	'0'個數:565

run_0/problem_20/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-11517	'1'個數:693	'0'個數:707

run_0/problem_20/infessible/r2_0.6 : 不可行:20	可行:0	種群總fit:-7402	'1'個數:551	'0'個數:849

run_0/problem_20/infessible/r2_0.7 : 不可行:10	可行:10	種群總fit:24159	'1'個數:401	'0'個數:999

run_0/problem_20/infessible/r2_0.8 : 不可行:3	可行:17	種群總fit:39011	'1'個數:290	'0'個數:1110

run_0/problem_20/infessible/r2_None : 不可行:15	可行:5	種群總fit:-9865	'1'個數:804	'0'個數:596

run_0/problem_21/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-27254	'1'個數:1096	'0'個數:304

run_0/problem_21/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-24178	'1'個數:994	'0'個數:406

run_0/problem_21/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-18335	'1'個數:836	'0'個數:564

run_0/problem_21/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-13338	'1'個數:693	'0'個數:707

run_0/problem_21/infessible/r2_0.6 : 不可行:20	可行:0	種群總fit:-8890	'1'個數:569	'0'個數:831

run_0/problem_21/infessible/r2_0.7 : 不可行:14	可行:6	種群總fit:9837	'1'個數:417	'0'個數:983

run_0/problem_21/infessible/r2_0.8 : 不可行:8	可行:12	種群總fit:22869	'1'個數:274	'0'個數:1126

run_0/problem_21/infessible/r2_None : 不可行:16	可行:4	種群總fit:-8979	'1'個數:623	'0'個數:777

run_0/problem_22/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-39962	'1'個數:1288	'0'個數:312

run_0/problem_22/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-32921	'1'個數:1137	'0'個數:463

run_0/problem_22/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-24234	'1'個數:945	'0'個數:655

run_0/problem_22/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-19878	'1'個數:813	'0'個數:787

run_0/problem_22/infessible/r2_0.6 : 不可行:20	可行:0	種群總fit:-11781	'1'個數:656	'0'個數:944

run_0/problem_22/infessible/r2_0.7 : 不可行:17	可行:3	種群總fit:5294	'1'個數:480	'0'個數:1120

run_0/problem_22/infessible/r2_0.8 : 不可行:7	可行:13	種群總fit:31038	'1'個數:351	'0'個數:1249

run_0/problem_22/infessible/r2_None : 不可行:16	可行:4	種群總fit:-18514	'1'個數:862	'0'個數:738

run_0/problem_23/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-41508	'1'個數:1276	'0'個數:324

run_0/problem_23/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-34389	'1'個數:1121	'0'個數:479

run_0/problem_23/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-25881	'1'個數:929	'0'個數:671

run_0/problem_23/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-22290	'1'個數:827	'0'個數:773

run_0/problem_23/infessible/r2_0.6 : 不可行:19	可行:1	種群總fit:-11284	'1'個數:662	'0'個數:938

run_0/problem_23/infessible/r2_0.7 : 不可行:20	可行:0	種群總fit:-5610	'1'個數:455	'0'個數:1145

run_0/problem_23/infessible/r2_0.8 : 不可行:11	可行:9	種群總fit:16484	'1'個數:317	'0'個數:1283

run_0/problem_23/infessible/r2_None : 不可行:16	可行:4	種群總fit:-21290	'1'個數:881	'0'個數:719

run_0/problem_24/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-24419	'1'個數:1257	'0'個數:343

run_0/problem_24/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-18541	'1'個數:1137	'0'個數:463

run_0/problem_24/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-14009	'1'個數:968	'0'個數:632

run_0/problem_24/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-6459	'1'個數:763	'0'個數:837

run_0/problem_24/infessible/r2_0.6 : 不可行:16	可行:4	種群總fit:12139	'1'個數:651	'0'個數:949

run_0/problem_24/infessible/r2_0.7 : 不可行:0	可行:20	種群總fit:68664	'1'個數:457	'0'個數:1143

run_0/problem_24/infessible/r2_0.8 : 不可行:0	可行:20	種群總fit:48722	'1'個數:311	'0'個數:1289

run_0/problem_24/infessible/r2_None : 不可行:12	可行:8	種群總fit:4311	'1'個數:833	'0'個數:767

run_0/problem_25/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-29800	'1'個數:1259	'0'個數:341

run_0/problem_25/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-25021	'1'個數:1115	'0'個數:485

run_0/problem_25/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-20519	'1'個數:976	'0'個數:624

run_0/problem_25/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-14319	'1'個數:830	'0'個數:770

run_0/problem_25/infessible/r2_0.6 : 不可行:18	可行:2	種群總fit:-2044	'1'個數:647	'0'個數:953

run_0/problem_25/infessible/r2_0.7 : 不可行:9	可行:11	種群總fit:35271	'1'個數:478	'0'個數:1122

run_0/problem_25/infessible/r2_0.8 : 不可行:2	可行:18	種群總fit:46000	'1'個數:359	'0'個數:1241

run_0/problem_25/infessible/r2_None : 不可行:12	可行:8	種群總fit:3899	'1'個數:791	'0'個數:809

run_0/problem_26/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-44701	'1'個數:1441	'0'個數:359

run_0/problem_26/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-39088	'1'個數:1306	'0'個數:494

run_0/problem_26/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-27858	'1'個數:1042	'0'個數:758

run_0/problem_26/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-23211	'1'個數:934	'0'個數:866

run_0/problem_26/infessible/r2_0.6 : 不可行:20	可行:0	種群總fit:-12145	'1'個數:699	'0'個數:1101

run_0/problem_26/infessible/r2_0.7 : 不可行:17	可行:3	種群總fit:2318	'1'個數:527	'0'個數:1273

run_0/problem_26/infessible/r2_0.8 : 不可行:4	可行:16	種群總fit:33948	'1'個數:365	'0'個數:1435

run_0/problem_26/infessible/r2_None : 不可行:16	可行:4	種群總fit:-13522	'1'個數:819	'0'個數:981

run_0/problem_27/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-43325	'1'個數:1417	'0'個數:383

run_0/problem_27/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-37456	'1'個數:1286	'0'個數:514

run_0/problem_27/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-28057	'1'個數:1078	'0'個數:722

run_0/problem_27/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-19616	'1'個數:876	'0'個數:924

run_0/problem_27/infessible/r2_0.6 : 不可行:20	可行:0	種群總fit:-12492	'1'個數:727	'0'個數:1073

run_0/problem_27/infessible/r2_0.7 : 不可行:18	可行:2	種群總fit:1779	'1'個數:528	'0'個數:1272

run_0/problem_27/infessible/r2_0.8 : 不可行:5	可行:15	種群總fit:40967	'1'個數:379	'0'個數:1421

run_0/problem_27/infessible/r2_None : 不可行:16	可行:4	種群總fit:-19035	'1'個數:968	'0'個數:832

run_0/problem_28/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-47161	'1'個數:1444	'0'個數:356

run_0/problem_28/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-38166	'1'個數:1281	'0'個數:519

run_0/problem_28/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-28615	'1'個數:1035	'0'個數:765

run_0/problem_28/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-23682	'1'個數:925	'0'個數:875

run_0/problem_28/infessible/r2_0.6 : 不可行:20	可行:0	種群總fit:-17343	'1'個數:752	'0'個數:1048

run_0/problem_28/infessible/r2_0.7 : 不可行:20	可行:0	種群總fit:-6754	'1'個數:552	'0'個數:1248

run_0/problem_28/infessible/r2_0.8 : 不可行:3	可行:17	種群總fit:40612	'1'個數:336	'0'個數:1464

run_0/problem_28/infessible/r2_None : 不可行:14	可行:6	種群總fit:-13094	'1'個數:860	'0'個數:940

run_0/problem_29/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-45681	'1'個數:1437	'0'個數:363

run_0/problem_29/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-37235	'1'個數:1248	'0'個數:552

run_0/problem_29/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-31127	'1'個數:1065	'0'個數:735

run_0/problem_29/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-23247	'1'個數:905	'0'個數:895

run_0/problem_29/infessible/r2_0.6 : 不可行:20	可行:0	種群總fit:-13411	'1'個數:682	'0'個數:1118

run_0/problem_29/infessible/r2_0.7 : 不可行:20	可行:0	種群總fit:-6842	'1'個數:525	'0'個數:1275

run_0/problem_29/infessible/r2_0.8 : 不可行:8	可行:12	種群總fit:28196	'1'個數:363	'0'個數:1437

run_0/problem_29/infessible/r2_None : 不可行:15	可行:5	種群總fit:-13496	'1'個數:751	'0'個數:1049

run_0/problem_30/infessible/r2_0.2 : 不可行:20	可行:0	種群總fit:-31021	'1'個數:1429	'0'個數:371

run_0/problem_30/infessible/r2_0.3 : 不可行:20	可行:0	種群總fit:-25105	'1'個數:1262	'0'個數:538

run_0/problem_30/infessible/r2_0.4 : 不可行:20	可行:0	種群總fit:-16124	'1'個數:1061	'0'個數:739

run_0/problem_30/infessible/r2_0.5 : 不可行:20	可行:0	種群總fit:-10979	'1'個數:906	'0'個數:894

run_0/problem_30/infessible/r2_0.6 : 不可行:17	可行:3	種群總fit:8919	'1'個數:755	'0'個數:1045

run_0/problem_30/infessible/r2_0.7 : 不可行:6	可行:14	種群總fit:59859	'1'個數:548	'0'個數:1252


# 相關性評估

In [ ]:
# # 初始解的相關性評估
# def similarity_analysis(population):
#     similarity_matrix = [[0] * log_pop_size for _ in range(log_pop_size)]
#     for i in range(log_pop_size):
#         for j in range(i+1,log_pop_size):
#             similarity = sum([1 for k in range(log_d) if log_pop_size[i][k] == log_pop_size[j][k]])
#             similarity_matrix[i][j] = similarity
#             similarity_matrix[j][i] = similarity
    
#     return similarity_matrix

# # 測試程式碼
# population = initial_log["initial_log_run_0_prob_0"]
# similarity_matrix = similarity_analysis(population)

# # 輸出相似性矩陣
# for row in similarity_matrix:
#     print(row)

In [ ]:
import random

# 定義種群大小和解的維度
population_size = 20
solution_dimension = 30

# 生成隨機的初始解
def generate_initial_solution():
    return [random.randint(0, 1) for _ in range(solution_dimension)]

# 生成初始種群
def generate_initial_population():
    return [generate_initial_solution() for _ in range(population_size)]

# 計算解的相似性分析
def similarity_analysis(population):
    similarity_matrix = [[0] * population_size for _ in range(population_size)]
    
    for i in range(population_size):
        for j in range(i+1, population_size):
            similarity = sum([1 for k in range(solution_dimension) if population[i][k] == population[j][k]])
            similarity_matrix[i][j] = similarity
            similarity_matrix[j][i] = similarity
    
    return similarity_matrix

# 測試程式碼
population = generate_initial_population()
print(population,"\n")
similarity_matrix = similarity_analysis(population)

# 輸出相似性矩陣
# for row in similarity_matrix:
#     print(row)

[[1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1], [0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0], [0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0], [1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0], [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0], [1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1], [0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0], [1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0], [1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1], [0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1], [1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1], [1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1], [0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1], [0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1], [0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0], [1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0], [1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1], [0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1]]

# 3.多樣性分析
多樣性分析是在算法優化和搜索領域中常用的一種技術，它有助於了解算法生成的解決方案之間的多樣性。以下是一些用於多樣性分析的常見方法：

解的分佈圖：繪製解決方案的分佈圖，通常用於二維或三維問題。這有助於可視化解的空間分佈。

解的距離分析：計算解決方案之間的距離或相似性，可以使用歐氏距離、曼哈頓距離、餘弦相似性等。較遠的解之間具有更高的多樣性。

解的聚類：應用聚類算法（如K均值聚類）來將解決方案劃分為不同的簇，每個簇表示相似的解。這有助於識別解決方案的群集。

分析前沿：在多目標優化中，繪製前沿圖，顯示不同權衡解決方案之間的多樣性。前沿圖顯示了權衡解之間的權衡關係。

種群多樣性指標：使用多樣性指標（如群集熵、多樣性指數等）來量化解決方案的多樣性水平。這些指標可以用於監視算法的多樣性進展。

解的差異度分析：比較解決方案與參考解之間的差異。參考解可以是已知的最優解或其他基準解。

變異分析：分析算法如何通過變異操作（如交叉、變異）生成不同的解。這有助於了解算法的多樣性來源。

局部搜索策略：引入局部搜索策略，以在一定程度上保留解的多樣性，例如，在搜索的早期階段採用多樣性較大的搜索策略。

可視化：使用可視化工具可視化解決方案的多樣性，例如，繪製解決方案的散點圖或散點矩陣。

敏感性分析：分析不同參數設置對解的多樣性的影響，確定哪些參數設置更有利於多樣性。

多樣性分析有助於評估算法的搜索策略，確保算法不僅找到高質量解，還具有多樣性，以避免陷入局部陷阱。這些方法通常需要與特定問題和優化算法相結合，以更好地理解解決方案的多樣性。

In [52]:
# 漢明距離
# 計算初始解的多樣性
def calculate_diversity(pop):
    num_solutions = len(pop)
    diversity = 0
    for i in range(num_solutions):
        for j in range(i+1, num_solutions):
            diversity += hamming_distance(pop.iloc[i,:], pop.iloc[j,:])
    diversity /= (num_solutions * (num_solutions - 1) / 2) # 正規化多樣性值
    return diversity

# 計算漢明距離
def hamming_distance(solution1, solution2):     
    distance = sum(bit1 != bit2 for bit1, bit2 in zip(solution1, solution2))
    return distance

# 執行計算初始解的多樣性
for i in range(run_time):
    initial_log["initial1_log_run_0_prob_01_r2_0"] = initial_log["initial1_log_run_0_prob_01_r2_0"].astype(int)
    pop = initial_log["initial1_log_run_0_prob_01_r2_0"].iloc[:, 1:-1]
    # print(pop)
    diversity = calculate_diversity(pop)
    print(f"第{i}次執行，初始解的多樣性：{diversity}") # 漢明距離

第0次執行，初始解的多樣性：9.473684210526315
第1次執行，初始解的多樣性：9.473684210526315
第2次執行，初始解的多樣性：9.473684210526315
第3次執行，初始解的多樣性：9.473684210526315
第4次執行，初始解的多樣性：9.473684210526315
第5次執行，初始解的多樣性：9.473684210526315
第6次執行，初始解的多樣性：9.473684210526315
第7次執行，初始解的多樣性：9.473684210526315
第8次執行，初始解的多樣性：9.473684210526315
第9次執行，初始解的多樣性：9.473684210526315